fix(service-portal): service portal - petitions
island-is/island.is pull request #10222
Opened 2023-02-27 14:14 UTC by albinagu

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-02-27 14:22 UTC, alexdiljar commented on libs/service-portal/petitions/README.md
> +Run `nx test service-portal-petitions` to execute the unit tests via [Jest](https://jestjs.io).
Maybe add to readme that you need to run endorsement service to test locally?

2023-02-28 15:41 UTC, thordurhhh commented on libs/service-portal/petitions/src/screens/PetitionsAdmin/index.tsx
> +              {'Lorem ipsum'}
Lorem ipsum 👀

2023-02-28 15:42 UTC, thordurhhh commented on libs/service-portal/petitions/src/screens/PetitionsAdmin/index.tsx
> +              {'Lorem ipsum'}
👁️

2023-02-28 15:51 UTC, thordurhhh commented on libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/downloadCSV.ts
> +        : 'data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,'
If you don't need the Excel format, the csvStringify function on line 25 could be simplified to:

```
    CSVStringify(data, (err, output) => {
      const encodedUri = encodeURI(`data:text/csv;charset=utf-8,${output}`)
      const link = document.createElement('a')
      link.setAttribute('href', encodedUri)
      link.setAttribute('download', name)
      document.body.appendChild(link)

      link.click()
    })
```

2023-02-28 15:56 UTC, thordurhhh requested changes
Just a few minor things in the comments.

2023-03-01 09:22 UTC, albinagu commented on libs/service-portal/petitions/src/screens/ViewPetitionAdmin/index.tsx
> +                ariaLabel={'Lorem ipsum'}
this functionality will be moved to the admin system, so i left these texts out while refactoring messages :3

2023-03-01 09:23 UTC, thordurhhh commented on libs/service-portal/petitions/src/screens/ViewPetitionAdmin/index.tsx
> +                ariaLabel={'Lorem ipsum'}
ahh alright

2023-03-01 09:59 UTC, alexdiljar reviewed
A couple of hard coded strings in there otherwise good

2023-03-01 09:59 UTC, alexdiljar commented on libs/service-portal/petitions/README.md
> +Run `nx test service-portal-petitions` to execute the unit tests via [Jest](https://jestjs.io).
Lets do it when er overhaul the whole documentation for the endorsement system :)

2023-03-01 10:01 UTC, alexdiljar approved these changes

2023-03-01 15:32 UTC, saevarma approved these changes
Core files LGTM

2023-03-02 10:48 UTC, merged