fix(j-s): Incident Description Autofill
island-is/island.is pull request #10265
Opened 2023-03-01 15:12 UTC by gudjong

# Incident Description Autofill

[Umferðarlagabrot - ölvunarakstur](https://app.asana.com/0/1199153462262248/1203865140443261/f)

## What

- Fixes incident description autofill removing duplicate text.
- Fixes drivers licence revoke request making it always available.

## Why

- Verified bugs.

## Screenshots / Gifs

<img width="397" alt="image" src="https://user-images.githubusercontent.com/795382/222180948-3c4ed315-3507-4460-bf69-6664f91d552d.png">

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-03-01 21:54 UTC, unakb requested changes
A few minor things, also one question. I noticed in text in the design docs that before the list relevant substances it says "í blóðsýni mældist ... ". Is the text there just out of date or do we need to add it into the relevantSubstances reason string

2023-03-01 21:54 UTC, unakb commented on apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
> -  const enableDriversLicenseSuspension = useMemo(
Please remove useMemo import as well

2023-03-01 21:54 UTC, unakb commented on apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
> +    console.log(acc)
```suggestion
```

2023-03-02 08:27 UTC, gudjong commented on apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
> +  console.log(offenses)
Sloppy 😊

2023-03-02 08:30 UTC, gudjong commented
> A few minor things, also one question. I noticed in text in the design docs that before the list relevant substances it says "í blóðsýni mældist ... ". Is the text there just out of date or do we need to add it into the relevantSubstances reason string?

Good point. I will investigate and fix.

2023-03-02 20:55 UTC, unakb approved these changes

2023-03-02 21:09 UTC, merged