chore(contentful): export data from contentful
island-is/island.is pull request #10432
Opened 2023-03-10 12:47 UTC by busla

- chore: added contentful exporter config
- fix: added content-export sh script

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-03-10 14:25 UTC, krrrrrrrrrrr approved these changes
LGTM

2023-03-10 14:56 UTC, brynjarorng requested changes

2023-03-10 15:00 UTC, busla commented on scripts/config/contentful-config.json
> +  ],
these are the only content-types needed for elasticsearch.

the idea is to export only the data that is needed to not have to preprocess data that will be discarded anyway.

but you are right, we should try to pull this object from the search-indexer app, good catch.

2023-03-10 15:01 UTC, busla commented on scripts/contentful-export.sh
> +# --space-id "$(get_param "/k8s/api-catalogue/CONTENTFUL_SPACE_ID")"
I just got clarification on why it was incorrect, will update, thanks.

2023-03-10 23:33 UTC, eirikurn reviewed
Please add some context to the PR so I know what I'm reviewing. What is the purpose of this?

2023-03-10 23:33 UTC, eirikurn commented on scripts/config/contentful-config.json
> +  ],
Hm. Doesn't the indexer also query/include all linked entries from these root entries? I assume the exporter doesn't do that.

Why not just export/backup everything?

2023-03-10 23:54 UTC, busla commented
this PR should be a draft still, will change.

PR description updated, thanks.

2023-03-10 23:58 UTC, busla commented on scripts/config/contentful-config.json
> +  ],
Just added description to the PR for better context.

According to @RunarVestmann these are the only content types remaped and added to the elastic index.

We could dump everything but why bother when we know what data will end up eventually in elastic?

2023-03-11 00:22 UTC, busla commented on scripts/config/contentful-config.json
> +  ],
The `queryEntries` list is copied from [here](https://github.com/island-is/island.is/blob/main/libs/cms/src/lib/environments/environment.ts#L5) but should be pulled in.

2023-03-13 14:17 UTC, closed without merging