added rightContent option on large checkboxes
island-is/island.is pull request #11281
Opened 2023-05-25 13:39 UTC by berglindoma13

# ...

Attach a link to issue if relevant

## What

Added an option of right content on large checkbox boxes

## Why

Needed for new citizenship application where tags need to be displayed on checkboxes

## Screenshots / Gifs

<img width="661" alt="After" src="https://github.com/island-is/island.is/assets/5684542/dea8f44d-6aa3-4ed3-b828-f10a3521dfbc">

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2023-05-30 13:37 UTC, Thorrik58 requested changes
Just minor comments, need to move the type change and the prop to the checkboxformfield story. Also some questions regarding the design process.

2023-05-30 13:37 UTC, Thorrik58 commented on libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
> +  field: CheckboxFieldPropsExtra
This shouldnt be the way to solve this, you should add this prop to the CheckBoxField in @island.is/application/types.

2023-05-30 13:37 UTC, Thorrik58 commented on libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
> +          rightContent={rightContent}
Was this change to the application system approved by design and added to the design system?
Also if this is a change to the field you should update the checkboxformfield story in storybook to demo the changes.

2023-10-21 08:12 UTC, andes-it commented
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

2023-11-09 08:03 UTC, andes-it commented
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

2023-11-15 08:03 UTC, andes-it commented
This PR closed its doors. Sat around for a day after the stale tag, then reckoned it's not worth the fuss.

2023-11-15 08:03 UTC, closed without merging