feat(old age pension): New application
island-is/island.is pull request #11584
Opened 2023-06-26 10:36 UTC by qdd1

# ...

Attach a link to issue if relevant

## What

New application: old age pension
It is still in development. We merge it to main to test connections and other things.
NOT GOING OUT TO PROD

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-06-26 10:40 UTC, thorkellmani requested changes
This is probably an accident

2023-06-26 10:40 UTC, thorkellmani commented on libs/service-portal/information/src/lib/messages.ts
> +  maritalþStatusMarried: {
```suggestion
  maritalStatusMarried: {
```
I'm guessing this was unintended

2023-06-26 12:31 UTC, eirikurn reviewed
Reviewed core files.

2023-06-26 12:31 UTC, eirikurn commented on libs/clients/national-registry/v2/src/lib/nationalRegistryClient.service.ts
> +    return cohabitants || null
Should default to [] for consistency?

2023-06-27 09:16 UTC, eirikurn approved these changes
Approving core files

2023-06-27 11:09 UTC, Thorrik58 requested changes
Feature flag is needed and there is an inconsistency with the fields, there are also a lot of comments that havent been removed too but I didnt want to mention them all.

2023-06-30 09:14 UTC, closed without merging