chore: remove .envrc
island-is/island.is pull request #11784
Opened 2023-08-01 13:11 UTC by busla

## What

Remove .envrc local config file

## Why

This file serves as a local config file for developers that use direnv and should not be committed. Developers have different direnv configurations.

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-08-01 13:13 UTC, peturgq approved these changes

2023-08-01 14:42 UTC, saevarma commented
I thought that the idea with `.envrc` was to share common unsensitive environment settings recommended for the repo, while programmers can use `.env.secret` to add custom (and sensitive) environment settings that are not committed.

Have you any thoughts on if/how we should share common env settings to developers?

2023-08-01 15:11 UTC, eirikurn requested changes
This is likely to change current dx workflows for all developers. E.g. with get-secrets. 

Imo should close this PR and discuss strategies for supporting alternate env workflows on Slack if it's important.

2023-08-03 15:26 UTC, busla commented
reopened the PR with a fix.

`direnv` will now load `.envrc.private` if it exists for custom config

2023-08-14 11:49 UTC, saevarma commented on apps/application-system/api/src/environments/environment.ts
Is this file change supposed to be part of this PR

2023-08-14 11:50 UTC, saevarma commented
You should update the PR's title to reflect the changes, for the generated changelog.

2023-08-17 06:08 UTC, saevarma approved these changes
LGTM

2023-08-21 16:42 UTC, merged