feat(j-s): Defender access changes
island-is/island.is pull request #12299
Opened 2023-10-04 09:32 UTC by unakb

[Aðgengi allra lögmanna (skráðir í lögmannaskrá) ](https://app.asana.com/0/1199153462262248/1205581325882016)

## What

Check lawyer registry when defenders without cases attempt to log in 

## Why

So the log in experience is better for defenders with no active cases

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-10-05 11:55 UTC, gudjong requested changes

2023-10-05 11:55 UTC, gudjong commented on apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
> +        res.clearCookie(CODE_VERIFIER_COOKIE.name, CODE_VERIFIER_COOKIE.options)
🧹

2023-10-05 11:55 UTC, gudjong commented on apps/judicial-system/api/src/app/modules/auth/auth.service.ts
> +import { type User, UserRole } from '@island.is/judicial-system/types'
Interesting, didn't know this was possible.

2023-10-05 11:55 UTC, gudjong commented on apps/judicial-system/api/src/app/modules/auth/auth.service.ts
> +      console.warn('Defender not found', error)
Please check specifically for a NotFoundException and only log and pass through for that exceptions. Also, consider logging as info. An error is logged futher down the call path "Blocking login attempt from an unauthorized user". That message should probably be logged as a warning instead.

If the exception is anything else it should be rethrown as it indicates an error on the backend or a problem with the connection to the backend.

2023-10-05 11:55 UTC, gudjong commented on apps/judicial-system/api/src/app/modules/auth/auth.service.ts
> +      console.warn('Defender not found in lawyer registry', error)
Consider logging as info for the same reason as above. Also, consider a more accurate message as the reason for the failure could be anything.

2023-10-05 11:55 UTC, gudjong commented on apps/judicial-system/api/src/app/modules/defender/defender.service.ts
> +    console.error('Failed to get lawyers:', reason)
Please remove console.log. If you still want to log, consider injecting a logger and use it instead. Also, please do not log as error as that will trigger alerts in operation.

2023-10-05 11:55 UTC, gudjong commented on apps/judicial-system/api/src/app/modules/auth/auth.service.ts
> +      console.warn('Defender not found', error)
Please do not use console logging. Instead, inject a logger and use it instead.

2023-10-05 11:55 UTC, gudjong commented on apps/judicial-system/api/src/app/modules/defender/defender.service.ts
> +    console.error('Failed to get lawyer:', reason)
Please do not use console logging and please do not log as error if you still want to log.

2023-10-06 08:14 UTC, brynjarorng approved these changes
LGTM

2023-10-06 16:46 UTC, gudjong approved these changes
Looks great

2023-10-06 18:49 UTC, merged