chore: move system test utils to new library
island-is/island.is pull request #12473
Opened 2023-10-23 10:35 UTC by lodmfjord

# Create new library for system tests

## What

Foundation for moving system tests to their own project folders.

## Why

Currently @island-is/qa is the code owner of all system tests, which is not ideal.

2023-10-23 10:50 UTC, AndesKrrrrrrrrrrr approved these changes

2023-10-28 08:03 UTC, saevarma requested changes
I assume that this PR is moving files from `apps/system-e2e/src/support|utils` to this new library. This PR should also remove those file from `apps/system-e2e` and import from this new library.

2023-10-28 08:03 UTC, saevarma commented on libs/testing-system/src/index.ts
Please export here directly and remove the `testing-system.ts` file.

2023-11-13 08:03 UTC, andes-it commented
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

2023-11-19 08:03 UTC, andes-it commented
This PR closed its doors. Sat around for a day after the stale tag, then reckoned it's not worth the fuss.

2023-11-19 08:03 UTC, closed without merging