feat(service-portal): Milage
island-is/island.is pull request #12571
Opened 2023-10-31 10:31 UTC by thordurhhh

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-11-24 14:26 UTC, Tryggvig requested changes

2023-11-24 14:26 UTC, Tryggvig commented on libs/service-portal/assets/src/components/MileageConfirmation/index.tsx
> +          Þú ert að fara að færa inn kílómetrastöðu: {formValue || '0 km'}
formatmessage?

2023-11-24 14:26 UTC, Tryggvig commented on libs/service-portal/assets/src/components/MileageConfirmation/index.tsx
> +          {formatMessage(m.save)}2
2?

2023-11-24 14:26 UTC, Tryggvig commented on libs/service-portal/assets/src/screens/Overview/Overview.tsx
> +
boop

2023-11-24 14:26 UTC, Tryggvig commented on libs/service-portal/assets/src/screens/VehicleMilage/VehicleMilage.tsx
> +                  offset={['0', '0', '0', '0', '0']}
['0'] ?

2023-11-24 14:27 UTC, thorkellmani requested changes
COOL, small issues tho

2023-11-24 14:27 UTC, thorkellmani commented on libs/api/domains/vehicles/src/lib/api-domains-vehicles-shared.resolver.ts
> +    this.logger.debug('resolveLastMileage data', res?.data)
```suggestion
```

2023-11-24 14:27 UTC, thorkellmani commented on libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
> +    @Inject(PdfApi) private vehiclesPDFApi: PdfApi,
```suggestion
    private vehiclesApi: VehicleSearchApi,
    private mileageReadingApi: MileageReadingApi,
    private vehiclesPDFApi: PdfApi,
```

2023-11-24 14:27 UTC, thorkellmani commented on libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts
> +  canRegisterMileage?: boolean | null
Do we need both?

2023-11-24 14:27 UTC, thorkellmani commented on libs/api/domains/vehicles/src/models/usersVehicles.model.ts
> +  canRegisterMileage?: boolean | null
Do we need both?

2023-11-24 14:27 UTC, thorkellmani commented on libs/clients/vehicles-mileage/src/lib/vehiclesMileageClient.config.ts
> +        },
Is there a purpose for elongating the timeout?

2023-11-24 14:27 UTC, thorkellmani commented on libs/clients/vehicles-mileage/src/lib/vehiclesMileageClient.service.ts
> +          timeout: config.fetch.timeout,
Why change timeout from default?

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/components/MileageConfirmation/index.tsx
> +const MileageConfirmation: FC<React.PropsWithChildren<Props>> = ({
Is this used?

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/lib/navigation.ts
> +                  name: m.vehicleMilage,
Milage u say? 🇮🇹

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/lib/navigation.ts
> +                  path: AssetsPaths.AssetsVehiclesDetailMilage,
Milage u say? 🇮🇹

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/lib/paths.ts
> +  AssetsVehiclesDetailMilage = '/eignir/okutaeki/min-okutaeki/:id/kilometrastada',
Milage u say? 🇮🇹

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/module.tsx
> +  import('./screens/VehicleMilage/VehicleMilage'),
Milage u say? 🇮🇹

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/module.tsx
> +        path: AssetsPaths.AssetsVehiclesDetailMilage,
Milage u say? 🇮🇹

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/module.tsx
> +        element: <VehicleMilage />,
Milage u say? 🇮🇹

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/screens/Overview/Overview.tsx
> +
cool

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/screens/VehicleDetail/VehicleDetail.tsx
> +                            ? AssetsPaths.AssetsVehiclesDetailMilage.replace(
Milage u say? 🇮🇹

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/assets/src/screens/VehicleMilage/VehicleMilage.tsx
> +        refetch()
Make a clear function or something?

2023-11-24 14:27 UTC, thorkellmani commented on libs/service-portal/core/src/lib/messages.ts
> +    id: 'service.portal:my-vehicles-milage',
Milage u say? 🇮🇹

2023-11-24 14:28 UTC, thordurhhh commented on libs/service-portal/assets/src/screens/VehicleMilage/VehicleMilage.tsx
> +                  offset={['0', '0', '0', '0', '0']}
lol

2023-11-24 14:49 UTC, thordurhhh commented on libs/api/domains/vehicles/src/models/usersVehicles.model.ts
> +  canRegisterMileage?: boolean | null
yes

2023-11-24 14:49 UTC, thordurhhh commented on libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts
> +  canRegisterMileage?: boolean | null
yes

2023-11-24 15:11 UTC, Thorrik58 approved these changes

2023-11-24 15:19 UTC, Tryggvig approved these changes
LGTM

2023-11-25 07:58 UTC, saevarma approved these changes
LGTM 🏎️

2023-11-25 07:58 UTC, saevarma commented on libs/clients/vehicles-mileage/src/lib/vehiclesMileageClient.service.ts
> +          name: 'clients-mileage-vehicles',
~ Just a nit pick but just match the library name
```suggestion
          name: 'clients-vehicles-mileage',
```

2023-11-25 07:58 UTC, saevarma commented on libs/api/domains/vehicles/src/lib/api-domains-vehicles-mileage.resolver.ts
> +  @Scopes(ApiScope.vehicles)
~ The `@Scopes` decorator can be on the class level so all methods are protected by it by default.

2023-11-25 07:58 UTC, saevarma commented on libs/api/domains/vehicles/src/lib/api-domains-vehicles-mileage.resolver.ts
> +  }
~ FYI async/await is unnecessary when returnin the promise from the service function. `return await` is only required inside a `try/catch` when you want to await the response to catch an error.
```suggestion
  getVehicleMileage(
    @Args('input') input: GetVehicleMileageInput,
    @CurrentUser() user: User,
  ) {
    return this.vehiclesService.getVehicleMileage(user, input)
  }
```

2023-11-27 09:46 UTC, brynjarorng approved these changes
LGTM

2023-11-27 13:32 UTC, merged