feat: add players
island-is/island.is pull request #12630
Opened 2023-11-06 14:24 UTC by thorkellmani

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-11-21 16:14 UTC, thordurhhh reviewed
Looking good. Minor comments.

2023-11-21 16:14 UTC, thordurhhh commented on libs/service-portal/core/src/components/VideoPlayer/VideoPlayer.tsx
> +                  title={isFullscreen ? 'Close fullscreen' : 'Open fullscreen'}
Add aria-label?

2023-11-21 16:14 UTC, thordurhhh commented on libs/service-portal/core/src/components/VideoPlayer/VideoPlayer.tsx
> +                  title={isMuted ? 'Unmute video' : 'Mute video'}
Add aria-label?

2023-11-21 16:14 UTC, thordurhhh commented on libs/service-portal/core/src/components/VideoPlayer/VideoPlayer.tsx
> +                      hasEnded
Add aria-label?

2023-11-21 16:14 UTC, thordurhhh commented on libs/service-portal/core/src/components/VideoPlayer/VideoPlayer.css.ts
> +      width: '546px',
What "random" number is this? 😵‍💫

2023-11-21 16:14 UTC, thordurhhh commented on libs/service-portal/core/src/components/AudioPlayer/AudioPlayer.tsx
> +    </GridColumn>
Remove?

2023-11-21 16:14 UTC, thordurhhh commented on libs/service-portal/core/src/components/AudioPlayer/AudioPlayer.tsx
> +                  title={isMuted ? 'Unmute audio' : 'Mute audio'}
Add aria-label?

2023-11-21 16:14 UTC, thordurhhh commented on libs/service-portal/core/src/components/AudioPlayer/AudioPlayer.tsx
> +                      hasEnded
add aria-label?

2023-11-22 10:50 UTC, thordurhhh commented on libs/service-portal/core/src/components/AudioPlayer/AudioPlayer.css.ts
> +      width: '546px',
👀

2023-11-22 10:51 UTC, thordurhhh approved these changes
Nice. Title and aria labels should probably be translated.
One `'546px'` in the audioplayer 👀

2023-11-22 14:25 UTC, Tryggvig requested changes

2023-11-22 14:25 UTC, Tryggvig commented on libs/service-portal/core/src/components/ProgressBar/ProgressBar.css.ts
> +  transition: 'transform 0.5s ease-out',
```suggestion
  transition: 'transform 0.2s linear',
```

2023-11-22 14:25 UTC, Tryggvig commented on libs/service-portal/core/src/components/AudioPlayer/AudioPlayer.css.ts
> +      width: '546px',
```suggestion
      width: theme.breakpoints.sm,
```

2023-11-22 15:12 UTC, Tryggvig approved these changes

2023-11-22 15:59 UTC, merged