feat(api): new hunting license client
island-is/island.is pull request #12833
Opened 2023-11-22 10:35 UTC by thorkellmani

## What

New client for the hunting license from Umhverfisstofnun

## Why

So we can display the license on Mínar Síður

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-12-21 08:03 UTC, andes-it commented
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

2024-01-06 08:03 UTC, andes-it commented
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

2024-02-07 08:03 UTC, andes-it commented
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

2024-02-23 08:03 UTC, andes-it commented
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

2024-03-15 12:28 UTC, busla requested changes

2024-03-15 12:28 UTC, busla commented on apps/api/infra/api.ts
>            'clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379',
```suggestion
          'redis-applications.internal:6379',
```

2024-03-15 12:31 UTC, thorkellmani commented on apps/api/infra/api.ts
>            'clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379',
dont know that this does but sure

2024-03-15 12:32 UTC, busla approved these changes
🙌🏼

2024-03-15 14:03 UTC, jonarnarbriem approved these changes

2024-03-15 14:18 UTC, thordurhhh approved these changes
Code owned files looking good 🚀

2024-03-15 16:51 UTC, saevarma approved these changes
LGTM

2024-03-15 16:51 UTC, saevarma commented on libs/auth-api-lib/seeders/data/client-licenses-ust.ts
Then you need to talk to Jón Arnar to generate and get the client's secret 

cc @jonarnarbriem

2024-03-15 16:51 UTC, saevarma commented on libs/clients/license-client/src/lib/clients/hunting-license-client/huntingLicenseClient.service.ts
> +const LOG_CATEGORY = 'adrlicense-service'
adr?

2024-03-18 09:11 UTC, thorkellmani commented on libs/auth-api-lib/seeders/data/client-licenses-ust.ts
yep, we're in cahoots

2024-03-18 09:12 UTC, thorkellmani commented on libs/clients/license-client/src/lib/clients/hunting-license-client/huntingLicenseClient.service.ts
> +const LOG_CATEGORY = 'adrlicense-service'
whoops 😵‍💫

2024-03-18 10:42 UTC, merged