feat(Vinnueftirlitid new template): change machine supervisor
island-is/island.is pull request #13335
Opened 2024-01-10 13:30 UTC by davidkef

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2024-01-11 08:36 UTC, oddsson approved these changes

2024-01-11 09:26 UTC, thorkellmani approved these changes
LGTM

2024-01-11 10:44 UTC, berglindoma13 requested changes
*Vantar validation á seinasta skref, kemur í console en koma engin villuskilaboð á skjáinn

2024-01-11 11:12 UTC, berglindoma13 requested changes

2024-01-11 11:12 UTC, berglindoma13 commented on libs/application/templates/aosh/change-machine-supervisor/src/forms/ChangeMachineSupervisorForm/InformationSection/supervisorSubSection.ts
> +            { value: 'ownerIsSupervisor', label: 'Eigandi er umráðamaður' },
Er þetta ekki þýðanlegt yfir á ensku?

2024-01-11 11:12 UTC, berglindoma13 commented on libs/application/templates/aosh/change-machine-supervisor/src/lib/messages/application.ts
> +    id: 'hlc.application:actionCardPrerequisites',
þarf að breyta úr hlc í aosh

2024-01-11 11:12 UTC, berglindoma13 commented on libs/application/templates/aosh/change-machine-supervisor/src/lib/messages/information.ts
> +        id: 'ta.cms.application:information.labels.supervisor.identicalError',
þarf að breyta út ta í aosh

2024-01-11 11:20 UTC, davidkef commented on libs/application/templates/aosh/change-machine-supervisor/src/forms/ChangeMachineSupervisorForm/InformationSection/supervisorSubSection.ts
> +            { value: 'ownerIsSupervisor', label: 'Eigandi er umráðamaður' },
Jú, ætti ég ekki að setja þetta bara í messages þar sem við getum verið með íslenska og enska þýðingu fyrir þetta

2024-01-11 14:02 UTC, davidkef commented on libs/application/templates/aosh/change-machine-supervisor/src/lib/messages/application.ts
> +    id: 'hlc.application:actionCardPrerequisites',
fixed

2024-01-11 14:02 UTC, davidkef commented on libs/application/templates/aosh/change-machine-supervisor/src/lib/messages/information.ts
> +        id: 'ta.cms.application:information.labels.supervisor.identicalError',
Fixed

2024-01-12 08:22 UTC, davidkef commented on libs/application/templates/aosh/change-machine-supervisor/src/forms/ChangeMachineSupervisorForm/InformationSection/supervisorSubSection.ts
> +            { value: 'ownerIsSupervisor', label: 'Eigandi er umráðamaður' },
Fixed

2024-01-15 09:44 UTC, saevarma approved these changes
Core file LGTM

2024-01-15 13:08 UTC, berglindoma13 approved these changes
LGTM

2024-01-15 15:02 UTC, davidkef commented on libs/application/templates/aosh/change-machine-supervisor/src/fields/MachinesField/MachineSelectField.tsx
> +export const MachineSelectField: FC<
Are you referring to the one coming from the Transfer-of-machine-ownership application? Which it is.
But I think that would be another task to rewrite that so it's coming from a shared place, same goes with Samgöngustofu. That would also need to be coming from a shared place if we are going that route.
Or are you talking about it being the same as the one in pickMachineSubSection, which it's not

2024-01-15 15:14 UTC, Thorrik58 approved these changes

2024-01-15 15:22 UTC, davidkef commented on libs/application/templates/aosh/change-machine-supervisor/src/fields/MachinesField/MachineSelectField.tsx
> +export const MachineSelectField: FC<
Yes I agree with you. Thank you, it'll be added to the our backlog as a task

2024-01-15 17:35 UTC, merged