fix(service-portal): UI fixes
island-is/island.is pull request #13424
Opened 2024-01-17 11:13 UTC by thorkellmani

## What

Various UI fixes for the rights portal

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2024-01-24 20:19 UTC, saevarma approved these changes
Core files LGTM

2024-01-25 09:39 UTC, thordurhhh commented on libs/service-portal/health/src/screens/Dentists/Dentists.tsx
> -    fetchPolicy: 'no-cache',
I believe this was in place to force fetch an update on redirect.

2024-01-25 09:39 UTC, thordurhhh requested changes
One minor comment, 🙌

2024-01-25 11:24 UTC, thordurhhh approved these changes
nice 🐬

2024-01-25 11:38 UTC, Tryggvig approved these changes
LGTM for ui

2024-01-25 14:25 UTC, merged