J s/context menu
island-is/island.is pull request #13452
Opened 2024-01-18 15:00 UTC by oddsson

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2024-01-23 17:25 UTC, gudjong requested changes
Some comments that need to be addressed.

2024-01-23 17:25 UTC, gudjong commented on apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealCaseFiles.tsx
> +          }
I tried this locally and only a single file is uploaded even if I select multiple files. Not sure what is happening.

2024-01-23 17:25 UTC, gudjong commented on apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
> +          return true
Returning from the loop means that we only try to upload the first file. The rest are ignored.

2024-01-24 15:06 UTC, oddsson commented on apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.tsx
> +                      <Box marginLeft={3}>
Good catch! Thanks..

2024-01-25 17:31 UTC, gudjong approved these changes

2024-01-26 14:33 UTC, merged