Feature/service auth api test
island-is/island.is pull request #1568
Opened 2020-10-27 15:17 UTC by stullifugl

# \<Description\>

Attach a link to issue if relevant

## What

Adding tests for project services-auth-api and fixing controllers and services to make tests run. Updating our seeders files to add necessary data into it and remove data that is not needed

## Why

To make tests run and updating seeders files

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against master before asking for a review

2020-10-28 10:42 UTC, dabbeg requested changes
Core files look good, but can you add your team in .github/CODEOWNERS for this project?
That way your team will be requested to review the changes you are making to your project

2020-10-28 15:19 UTC, stullifugl commented
> Core files look good, but can you add your team in .github/CODEOWNERS for this project?
> That way your team will be requested to review the changes you are making to your project

Done

2020-10-29 10:13 UTC, dabbeg commented
> I got an error saying that fuglar is not a team. Don´t know why but this request is needed so I will find it out later

@sindrig what does one need to do to add a team to the CODEOWNERS file?

2020-10-29 10:16 UTC, dabbeg approved these changes

2020-10-29 10:46 UTC, merged