Judicial System: Updates ruling pdf for pilot
island-is/island.is pull request #1600
Opened 2020-10-28 18:48 UTC by gudjong

# PDF Update

https://app.asana.com/0/1197628843274291/1198899954964768

## What

☝️ 

## Why

Feedback from users.

## Screenshots / Gifs

See attachments in issue ☝️ 

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against master before asking for a review

2020-10-28 20:34 UTC, addi requested changes

2020-10-28 20:34 UTC, addi commented on apps/judicial-system/api/src/app/modules/case/case.pdf.ts
> +      `Þinghaldi lauk þann frá kl. ${formatDate(
Þetta skilar: Þinghaldi lauk þann frá kl. 28. október 2020 kl. 14:45

er þetta ekki eitthvað bogið?

2020-10-28 23:13 UTC, gudjong commented on apps/judicial-system/api/src/app/modules/case/case.pdf.ts
> +      `Þinghaldi lauk þann frá kl. ${formatDate(
Kengbogið. Sama vandamál í "Þinghald hófst..." Veit ekki hvernig ég missti af þessu ⏩

2020-10-29 08:27 UTC, oddsson approved these changes

2020-10-29 08:30 UTC, addi approved these changes
LGTM

2020-10-29 09:12 UTC, merged