Add lint rule "no-restricted-imports" for lodash and date-fns
island-is/island.is pull request #1634
Opened 2020-10-30 11:25 UTC by arnifreyrs

# \<Reduce bundle size due to importing lodash and date-fns\>

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against master before asking for a review

2020-10-30 11:28 UTC, darrikonn approved these changes
AWESOME!

2020-10-30 11:40 UTC, jeremybarbet approved these changes
LGTM

2020-10-30 11:50 UTC, gudjong approved these changes
Nice

2020-10-30 11:54 UTC, gudjong requested changes
I approved this a bit quickly. There is a failing test in the judicial system backend. I'll can investigate if you like.

2020-10-30 12:13 UTC, arnifreyrs commented
I am looking into it @gudjong

2020-10-30 16:25 UTC, Thorrik58 approved these changes
Looks good to me!

2020-11-02 08:41 UTC, jeremybarbet approved these changes
LGTM

2020-11-02 10:04 UTC, saevarma requested changes

2020-11-02 10:30 UTC, arnifreyrs commented on libs/judicial-system/formatters/src/lib/formatters.ts
> +import { format, parseISO, isValid } from 'date-fns'
I tried to have this the new way for 2 hours, but doing that introduced some test failures that required immense changes to tsconfig.json for this lib and the app that required it so I just gave up after that long. I feel like this should just slide and be fixed if wished by the owners of the judicial system.

2020-11-02 10:42 UTC, saevarma commented on libs/judicial-system/formatters/src/lib/formatters.ts
> +import { format, parseISO, isValid } from 'date-fns'
Ok sounds valid.

2020-11-02 10:42 UTC, saevarma approved these changes

2020-11-02 13:22 UTC, darrikonn approved these changes

2020-11-02 13:46 UTC, merged