feat(j-s): Service certificate pdf
island-is/island.is pull request #16463
Opened 2024-10-18 11:56 UTC by oddsson

# Service certificate pdf

[Asana](https://app.asana.com/0/1199153462262248/1208331028610840/f)

## What

Implement a service certificate pdf. 

## Why

This document is needed to be able to tell that a service was done correctly after the case has been archived from RVG

## Screenshots / Gifs

<img width="794" alt="Screenshot 2024-10-17 at 13 42 50" src="https://github.com/user-attachments/assets/c2282261-85a1-4401-9039-c85e1de96d66">
<img width="791" alt="Screenshot 2024-10-17 at 13 44 47" src="https://github.com/user-attachments/assets/40c87c3e-633d-4d8f-afee-de7a9e9a9423">
<img width="791" alt="Screenshot 2024-10-17 at 13 46 49" src="https://github.com/user-attachments/assets/32675764-8146-4dc6-9b6b-75ed98e9afee">

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2024-10-18 18:00 UTC, gudjong requested changes
Looks good, except defenders will see a button to open the service certificate, but will not be able to open it. Do give them access, code needs to be added to limited access controllers in the api and backend.

2024-10-21 14:50 UTC, gudjong approved these changes
Looks good. One suggestion.

2024-10-21 14:50 UTC, gudjong commented on apps/judicial-system/backend/src/app/modules/subpoena/limitedAccessSubpoena.controller.ts
> +    if (!subpoena) {
Note that there is an alternative subpoena guard that takes care of this. Please consider moving the `SubpoenaExistsOptionalGuard` to the `getSubpoenaPdf` endpoint and use `SubpoenaExistsGuard` for this endpoint. That will allow you to remove this check.

2024-10-21 17:37 UTC, gudjong approved these changes
Nice. Some failing tests.

2024-10-21 21:14 UTC, oddsson commented on apps/judicial-system/backend/src/app/modules/subpoena/test/limitedAccessSubpoenaController/limitedAccessSubpoenaControllerGuards.spec.ts
> +    expect(guards).toHaveLength(6)
Yes it still used in this controller but not on the controller itself but rather an endpoint within the controller, which this test is not testing

2024-10-21 21:17 UTC, merged