Judicial-system/Strict TS setting pt2
island-is/island.is pull request #1826
Opened 2020-11-10 15:35 UTC by oddsson

# Prosecutor flow now uses strict TS

https://app.asana.com/0/1197628843274291/1199143603683037

## What

See ☝️

## Why

It's a requirement from island-is. Also it's generally good practice.

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against master before asking for a review

2020-11-11 08:23 UTC, gudjong reviewed
Have a couple of comments.

2020-11-11 08:23 UTC, gudjong commented on apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
> +                            if (restrictions) {
Why guard against this here, but not above?

2020-11-11 08:23 UTC, gudjong commented on apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.tsx
> +                          if (copyOfState.custodyRestrictions) {
Consider copying the value in the judge flow. By copying this way, any values set by the judge will be overwritten here. Or am I missing something?

2020-11-11 15:49 UTC, addi requested changes
Vantar smá púss.

2020-11-11 15:49 UTC, addi commented on apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
> +  const [workingCase, setWorkingCase] = useState<Case>(null)
Vorum við ekki búin að leysa eitthvað svona?

2020-11-11 15:49 UTC, addi commented on apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
> +    if (id && workingCase === null && data) {
Þarft ekki að hafa id checkið þarna. Það er ekkert working case án id, id er hvort sem er ekki notað í effectinu.

2020-11-11 15:49 UTC, addi commented on apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.tsx
> +  const [workingCase, setWorkingCase] = useState<Case>()
Hérna erum við td ekki með null í default value. Sjá comment á RulingStepOne.tsx

2020-11-12 12:58 UTC, addi approved these changes

2020-11-12 12:59 UTC, merged