User profile service : update user profile readme
island-is/island.is pull request #2216
Opened 2020-12-14 13:06 UTC by obmagnusson

# \<Description\>

Attach a link to issue if relevant

## What

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2020-12-14 13:08 UTC, arnifreyrs requested changes

2020-12-14 13:08 UTC, arnifreyrs commented on apps/services/user-profile/README.md
> +http://localhost:3333/swagger/#/default
I just merged a PR where I change the port to 3366

2020-12-14 13:25 UTC, obmagnusson commented on apps/services/user-profile/README.md
> +http://localhost:3333/swagger/#/default
```suggestion
http://localhost:3366/swagger/#/default
```

2020-12-14 13:28 UTC, obmagnusson commented on apps/services/user-profile/README.md
> +A service that is responsible for providing and storing User profile info. With the users National Id stores contact info and preferred locale. Additional responsibility is a verification process of
```suggestion
A service that is responsible for providing and storing User profile info. With the users National Registration id stores contact info and preferred locale. Additional responsibility is a verification process of email and mobile phone.
```

2020-12-14 13:29 UTC, Thorrik58 approved these changes

2020-12-16 10:44 UTC, arnifreyrs approved these changes

2020-12-16 10:53 UTC, merged