Sidebar layout padding
island-is/island.is pull request #2220
Opened 2020-12-14 15:08 UTC by siggakogk

# Layout spacing

Remove styling from rich text component
Make sidebarlayout handle padding for it's content
Move richtext into grid layout in newsitem and life events (where sidebarlayout is not being used)

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2020-12-14 17:18 UTC, barabrian requested changes
minor comments

2020-12-14 17:18 UTC, barabrian commented on apps/web/components/RichText/RichText.tsx
> +    children
what is this code doing?

2020-12-14 17:18 UTC, barabrian commented on apps/web/components/RichText/RichText.tsx
> +    children
maybe remove the if statement if this is no longer relevant

2020-12-14 17:18 UTC, barabrian commented on apps/web/screens/AboutSubPage/AboutSubPage.tsx
> +                isMenuDialog={true}
```suggestion
                isMenuDialog
```

2020-12-14 17:18 UTC, barabrian commented on apps/web/screens/AboutPage/AboutPage.tsx
>          isSticky={false}
is this not false by default?

2020-12-15 08:40 UTC, siggakogk commented on apps/web/screens/AboutPage/AboutPage.tsx
>          isSticky={false}
it's true by default

2020-12-15 09:40 UTC, barabrian approved these changes

2020-12-15 09:50 UTC, merged