Judicial system/Alternative travel ban implementation
island-is/island.is pull request #2421
Opened 2021-01-06 14:04 UTC by oddsson

# Implements alternative travel ban for prosecutors

https://app.asana.com/0/322488613152836/1199571460336671

## What

Prosecutors can now select _alternative travel ban_ when creating a detention request.

## Why

It's a requirement.

## Screenshots / Gifs

![screencapture-localhost-4200-stofna-krofu-lagaakvaedi-031e55ac-56ef-41ba-b615-60266fa5a69f-2021-01-06-08_29_31](https://user-images.githubusercontent.com/3789875/103746754-81ea5080-4ff9-11eb-8d1e-cb51cda43368.png)

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-01-07 16:09 UTC, gudjong requested changes

2021-01-07 16:09 UTC, gudjong commented on apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepThree/StepThree.tsx
> +                    label="Gæsluvarðhald til"
Samkvæmt hönnun ætti þetta að vera "Gæsluvarðhald / farbann til".

2021-01-08 10:47 UTC, oddsson commented on apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepTwo/StepTwo.spec.tsx
> +  test('should not allow users to continue unless every required field has been filled out-rass', async () => {
```suggestion
  test('should not allow users to continue unless every required field has been filled out', async () => {
```

2021-01-08 11:10 UTC, gudjong approved these changes

2021-01-08 12:14 UTC, barabrian approved these changes
lgtm

2021-01-08 13:45 UTC, gudjong approved these changes

2021-01-08 13:50 UTC, DavidBachmann approved these changes

2021-01-08 13:50 UTC, merged