refactor: better gitbook script, organise assets better and more documentation
island-is/island.is pull request #2443
Opened 2021-01-08 10:48 UTC by jeremybarbet

## What

- Add whitelist for full uppercase words (e.g. API, CMS, etc..)
- Add an exception for CONNECTIVES word to be capitalized if it's the first word of the title
- Remove `.gitbook/assets` directory and move assets to the directory where it's used under an `assets` directory
- Add documentation about README.md, links, and assets
- Fix existing documentation to render properly links and structure

2021-01-08 10:50 UTC, sindrig submitted a review, later dismissed
LGTM

2021-01-11 09:12 UTC, darrikonn requested changes
Looks good!

2021-01-11 09:12 UTC, darrikonn commented on scripts/gitbook.js
> +const WHITELIST = 'api css cms adr http nova sms ui'
`UPPERCASE_WHITELIST`

Had to read the code to see what it was a whitelist for.

2021-01-11 09:36 UTC, darrikonn approved these changes

2021-01-12 11:33 UTC, sindrig commented
formatting seems to have some problems with SUMMARY.md now: https://github.com/island-is/island.is/pull/2443/checks?check_run_id=1680227716

2021-01-12 15:11 UTC, darrikonn approved these changes

2021-01-12 15:16 UTC, merged