Judicial System: Format requested custody restrictions
island-is/island.is pull request #2953
Opened 2021-02-18 20:35 UTC by gudjong

# Format requested custody restrictions

Galli í uppbyggingu tilhögunar á farbanni

## What

☝️ 

## Why

Looks better

## Screenshots / Gifs

![image](https://user-images.githubusercontent.com/795382/108418256-e586b100-7228-11eb-8248-421f7692f7c0.png)

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-02-18 22:01 UTC, addi requested changes

2021-02-18 22:01 UTC, addi commented on apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
> +            !!theCase.requestedCustodyRestrictions?.includes(
Ég er ekki hrifinn af !! trixinu, en ég væri líka til í að hafa formatProsecutorDemands() fyrir utan objectið. Var dáldið ruglingslegt að lesa kóðann.

Þarf ekki líka að vista þetta default value á serverinn?

2021-02-19 09:23 UTC, gudjong commented on apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
> +            !!theCase.requestedCustodyRestrictions?.includes(
Default er null. Getum nota `|| false` í staðinn fyrir !!
Vandamálið sem ég var að leysa var að typescript vill ekki "posibly undefined" sem boolean parameter. Sú villa birtist eftir að ég tók requestedCustodyRestrictions út úr skilirðinu fyrir ofan.

2021-02-19 09:26 UTC, gudjong commented on apps/judicial-system/web/src/routes/Judge/CourtRecord/CourtRecord.tsx
>              ),
```suggestion
            theCase.requestedCustodyRestrictions?.includes(
              CaseCustodyRestrictions.ISOLATION,
            ) || false,
```

2021-02-19 09:35 UTC, addi submitted a review, later dismissed

2021-02-19 10:29 UTC, addi approved these changes

2021-02-19 10:35 UTC, merged