Fix(Judicial-system): Fixed update / pdf generation race condition
island-is/island.is pull request #3181
Opened 2021-03-09 13:57 UTC by addi

https://app.asana.com/0/1108390964845040/1199999639914923

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-03-09 14:11 UTC, oddsson approved these changes

2021-03-11 08:15 UTC, gudjong requested changes

2021-03-11 08:15 UTC, gudjong commented on apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.tsx
> +              disabled={isUpdating}
Disabling the PDF button is a good idea, but does not resolve the issue reported. That had to do with the signature button.

It is possible that the issue was incorrectly reported. If not, however, then the signature button needs to be disabled as well.

2021-03-12 10:33 UTC, gudjong approved these changes

2021-03-12 10:46 UTC, merged