feat(judicial-system): Add isolation end date
island-is/island.is pull request #3230
Opened 2021-03-12 13:26 UTC by oddsson

# Isolation end date

https://app.asana.com/0/322488613152836/1199874241701810

## What

Add the ability to enter an isolation end date. Note that

- Isolation can never be set in the past.
- Isolation end date can not be set after the custody end date.

## Why

Isolation should is not always as long as the custody.

## Screenshots / Gifs

![Screen Shot 2021-03-12 at 13 23 44](https://user-images.githubusercontent.com/3789875/110945913-32483e00-8336-11eb-8f8c-f60dd2ee1db9.png)
![Screen Shot 2021-03-12 at 13 23 28](https://user-images.githubusercontent.com/3789875/110945917-33796b00-8336-11eb-8f24-ac72d4741e33.png)
![Screen Shot 2021-03-12 at 13 23 16](https://user-images.githubusercontent.com/3789875/110945919-34120180-8336-11eb-8476-8500ac91b4cc.png)

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-03-15 09:29 UTC, gudjong requested changes

2021-03-15 09:29 UTC, gudjong commented on apps/judicial-system/backend/migrations/20210311090927-update-case.js
> +          defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
```suggestion
          type: Sequelize.DATE,
```

We use timestamps for 'created' and 'modified' but simple 'date' for other date fields and no default values.

2021-03-15 09:29 UTC, gudjong commented on apps/judicial-system/backend/test/e2e.spec.ts
> +  expect(caseOne.isolationTo || null).toBe(caseTwo.isolationTo || null)
isolationTo must also be handled in caseToCCase the same way other date fields are handled.

2021-03-15 14:08 UTC, gudjong approved these changes

2021-03-16 08:23 UTC, jeremybarbet approved these changes
LGTM

2021-03-16 08:24 UTC, siggakogk approved these changes
LGTM 🐶

2021-03-16 09:40 UTC, merged