Service portal/download service
island-is/island.is pull request #3380
Opened 2021-03-29 10:59 UTC by obmagnusson

# \<Description\>

Download service for a more robust flow when opening and downloading files in React apps.

## What

1. New Rest API app Created Download Service 
2. Added a new FromBody Authentication stragety.
3. Refactor Document client out of /api/domains
4. Adopted Service Portal Documents to this new stragety

## Why

1. We need a rest client for the file stream as GQL does not support it.
2. Need this so we can get the token from the Client to the Download Service using Form POST. And we wont need a second client to provide authentication in a new tab.
3. As now two apps are using the same client. This makes code sharing easier.
4. To use the new functionality.

## Screenshots / Gifs

Overview of the Download Service
![dlService](https://user-images.githubusercontent.com/2643113/112824415-06d58b00-907a-11eb-83e6-4933f27c8c0c.png)

![download-serivce](https://user-images.githubusercontent.com/2643113/112827263-9f213f00-907d-11eb-913a-a111a13c9bab.gif)

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-03-29 11:08 UTC, obmagnusson commented
There is currently no deployment for this.

2021-03-30 16:22 UTC, andriandresson requested changes
One comment

2021-03-30 16:30 UTC, obmagnusson commented on apps/download-service/src/environments/environment.ts
> +    basePath: 'https://test-skjalabirting-island-is.azurewebsites.net',
Hmm maybe it is better to not include that test url in the repo. I dont know.  Just one more thing to export during development.

2021-03-30 16:30 UTC, obmagnusson commented on apps/download-service/src/environments/environment.ts
> +    basePath: 'https://test-skjalabirting-island-is.azurewebsites.net',
Hmm maybe it is better to not include that test url in the repo. I dont know.  Just one more thing to export during development.

2021-03-30 16:51 UTC, andriandresson approved these changes
LGTM

2021-03-31 10:42 UTC, valurefugl approved these changes

2021-03-31 13:02 UTC, pshomov commented
Do we need to have a separate domain(download.island.is) for the download service? Would be best to keep it all under island.is.

2021-03-31 13:27 UTC, obmagnusson commented
Well the idea is as it is an api that it would live under the domain 'api' (api.island.is). That diagram may be a bit out of date sry bout that.

2021-04-12 11:25 UTC, eirikurn approved these changes
LGTM

2021-04-12 11:43 UTC, merged