Changing endorsement form to be able to sign
island-is/island.is pull request #3644
Opened 2021-04-28 09:48 UTC by siggakogk

# \<Description\>

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-04-28 10:10 UTC, barabrian approved these changes
LGTM

2021-04-29 16:02 UTC, stefanhar commented on yarn.lock
> +jose@^1.27.2, jose@^1.28.0:
Is this intentional

2021-04-29 16:03 UTC, stefanhar requested changes
Had to leave a comment 🙄

2021-04-30 08:55 UTC, stefanhar approved these changes

2021-05-02 10:22 UTC, merged