fix(judicial-system): Removes logging of email addresses and mobile numbers on error
island-is/island.is pull request #3688
Opened 2021-04-30 18:01 UTC by gudjong

# Removes logging of email addresses and mobile numbers on error

https://app.asana.com/0/1199153462262248/1200214011389030

## What

☝️ 

## Why

Specify why you need to achieve this

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2021-04-30 20:43 UTC, oddsson requested changes
There are a few more that I think we need to remove

128: auth.controller.ts

75: case.service.ts

97: notification.service.ts
146: notification.service.ts

50: user.service.ts
80: user.service.ts

2021-05-05 08:57 UTC, gudjong commented
Other changes may be need, but I was just addressing specific recommendations from Syndis. I will take a look.

2021-05-05 09:04 UTC, gudjong commented
What I did:

128: auth.controller.ts - removed the nationalId

75: case.service.ts - removed the email address

97: notification.service.ts - this had already been address in the original PR
146: notification.service.ts - this had already been address in the original PR

50: user.service.ts - removed the national id
80: user.service.ts - removed the national id

2021-05-05 09:11 UTC, oddsson approved these changes

2021-05-05 09:15 UTC, merged