feature(judicial-system): Upload Request to Court
island-is/island.is pull request #3747
Opened 2021-05-06 15:24 UTC by gudjong

# Upload Request to Court

https://app.asana.com/0/1199153462262248/1199961024543213

## What

☝️ 

## Why

Convenient, less manual work, more secure, ...

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-05-14 09:05 UTC, oddsson approved these changes

2021-05-14 15:21 UTC, darrikonn approved these changes

2021-05-14 15:21 UTC, darrikonn requested changes
The type dep should be added as a dev dep

2021-05-14 16:32 UTC, gudjong commented
> The type dep should be added as a dev dep

Fixed

2021-05-17 09:10 UTC, sindrig approved these changes
![LGTM](https://www.lgtm.app/p/7AwhYVcRh)

2021-05-17 09:37 UTC, darrikonn approved these changes

2021-05-17 10:30 UTC, merged