bulk upload in party application
island-is/island.is pull request #4092
Opened 2021-06-07 10:57 UTC by albinagu

Bulk Upload in party application

on success:
![Screenshot 2021-06-07 at 10 56 29](https://user-images.githubusercontent.com/47886428/121005194-13afe280-c77f-11eb-92c2-6cbb7b28ac5d.png)

on error:
![Screenshot 2021-06-07 at 10 57 25](https://user-images.githubusercontent.com/47886428/121005267-2e825700-c77f-11eb-8612-dc6334e15c26.png)

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-06-07 11:03 UTC, siggakogk commented on libs/application/templates/party-application/src/fields/BulkUpload/index.tsx
> +  LoadingIcon,
LoadingIcon has been deprecated, you should use LoadingDots instead :D

2021-06-07 14:50 UTC, siggakogk commented on libs/application/templates/party-application/src/forms/CollectEndorsementsForm.ts
> -            buildCheckboxField({
remove commented code

2021-06-07 14:52 UTC, siggakogk commented on libs/application/templates/party-application/src/lib/messages.ts
> +    },
these strings already exist under collectEndorsements, maybe move the "uploadFail" string to collectEndorsements section and delete this section one.. or vice versa, just avoid duplication 😛

2021-06-08 14:52 UTC, siggakogk approved these changes

2021-06-09 11:00 UTC, eirikurn approved these changes

2021-06-09 11:02 UTC, eirikurn requested changes
Wait, there's already a node-xlsx package in the repo. I'd like to avoid having two packages solving the same problem. Please evaluate.

2021-06-09 11:11 UTC, eirikurn approved these changes
Looking further into this, I see you're loading `xlsx` in the browser, and `node-xlsx` uses `xlsx` behind the scenes. Please be aware that `xlsx` is [900kb of minified js](https://bundlephobia.com/package/xlsx@0.17.0), so we need to make sure to not load it until needed. Afaik the applications and/or custom components are lazily loaded.

Regarding `node-xlsx`, I can only see it used in one place in the `voter-registry`, so we should get rid of it and just use `xlsx` everywhere instead, if possible.

cc @stefanhar

2021-06-09 13:10 UTC, stefanhar commented
> Looking further into this, I see you're loading `xlsx` in the browser, and `node-xlsx` uses `xlsx` behind the scenes. Please be aware that `xlsx` is [900kb of minified js](https://bundlephobia.com/package/xlsx@0.17.0), so we need to make sure to not load it until needed. Afaik the applications and/or custom fields are lazily loaded in separate bundles.
> 
> Regarding `node-xlsx`, I can only see it used in one place in the `voter-registry`, so we should get rid of it and just use `xlsx` everywhere instead, if possible.
> 
> cc @stefanhar

It's used in both the `voter-registry` and `party-letter-registry`.
I'll convert those services to use `xlsx` and remove the `node-xlsx` dependency in a separate PR

2021-06-10 09:11 UTC, merged