feat(financial aid): Adding Web Veita to tsconfig and Identicon package
island-is/island.is pull request #4294
Opened 2021-06-23 15:42 UTC by MargretFinnboga

## Adding Web Veita to tsconfig and Identicon package

## What

Needed to add Web Veita to tsconfig for imports
Added Identicon package for Web Veita to create unique profile images for applicants 

## Why
tsconfig: clarity in code
package: for better visualization experience for staff working with the applications  

## Screenshots / Gifs

<img width="270" alt="Screenshot 2021-06-23 at 15 00 56" src="https://user-images.githubusercontent.com/62568905/123126962-5e954f80-d439-11eb-867e-ca60ffe4479c.png">:

## Checklis

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2021-06-23 16:50 UTC, addi approved these changes

2021-06-24 10:13 UTC, eirikurn approved these changes
LGTM. It might be good to open a follow up discussion in the design discipline, if we want to use identicon in our design system for this use case (or if there are specific settings or alternatives we want to use).

2021-06-24 10:13 UTC, eirikurn commented on package.json
> +    "@types/identicon.js": "^2.3.0",
Please remove the ^

2021-06-24 10:13 UTC, eirikurn commented on package.json
> +    "identicon.js": "^2.3.3",
Please remove the ^

2021-06-24 10:13 UTC, eirikurn requested changes
Sorry. Forgot the dep versions. Please fix those before merging :)

2021-06-24 12:22 UTC, eirikurn approved these changes

2021-06-27 23:49 UTC, merged