feat(an): Accident details screen
island-is/island.is pull request #4568
Opened 2021-07-19 14:10 UTC by Thorrik58

# Accident details screen

Attach a link to issue if relevant

## What

Adding accident details screen

## Why

So the user can specify the details of the accident

## Screenshots / Gifs

![image](https://user-images.githubusercontent.com/2814693/126173430-439926a4-7ce6-4f81-9810-1ed2ab142fec.png)

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-07-19 16:21 UTC, bensijons requested changes

2021-07-19 16:21 UTC, bensijons commented on libs/application/templates/accident-notification/src/utils/index.ts
> +}
Perhaps add some tests for this?

2021-07-20 09:30 UTC, Thorrik58 commented on libs/application/templates/accident-notification/src/utils/index.ts
> +}
Good point, added

2021-07-20 09:34 UTC, bensijons approved these changes

2021-07-20 10:03 UTC, pshomov approved these changes
LGTM

2021-07-20 18:05 UTC, merged