feat(financial-aid): Staff can comment on application
island-is/island.is pull request #4796
Opened 2021-08-30 17:44 UTC by MargretFinnboga

# Staff can comment on application

https://app.asana.com/0/1200826552987384/1200876741986739

## What

Staff can comment on application. State was changed to event type and amount, and staff comment added.
Added to navigation user 

## Why

Required from customer 
Better user experience 

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2021-08-31 14:15 UTC, Rikkiabb requested changes

2021-08-31 15:52 UTC, MargretFinnboga commented on apps/financial-aid/backend/migrations/20210830110934-update-application_events.js
> +          'amount',
new table, id, created. application_id, comment. event_type, amount, staff_comment

2021-08-31 15:53 UTC, MargretFinnboga commented on apps/financial-aid/backend/migrations/20210830110934-update-application_events.js
> +          'amount',
Lets changed it up, to id, created, application_id, event_type and comment

2021-09-01 09:52 UTC, MargretFinnboga commented on apps/financial-aid/web-veita/src/components/CommentSection/CommentSection.tsx
> +    if (isCreatingApplicationEvent === false && staffComment) {
Yass good suggestion

2021-09-01 14:42 UTC, Rikkiabb requested changes

2021-09-01 14:42 UTC, Rikkiabb commented on libs/financial-aid/shared/src/lib/types.ts
> +// export enum (ApplicationEventType & ApplicationState)
Let's throw this in the trash and forget about it

2021-09-01 15:17 UTC, Rikkiabb approved these changes
🐰

2021-09-01 15:37 UTC, merged