Dl/fix
island-is/island.is pull request #4837
Opened 2021-09-02 15:15 UTC by alexandradilja

# ...

Small look fixes on driving license and driving assessment applications

## What

- Change ökuskírteini title to fullnaðarskírteini
- Change data provider error in driving license
- Spacing between name and email in driving assessment
- radio buttons in mobile view
- Images on loading screens in payment

## Why

For a better user experience

## Screenshots / Gifs

![Screenshot 2021-09-02 at 15 12 35](https://user-images.githubusercontent.com/42963845/131870077-72731464-1585-4a4f-bd25-6b7c97050cb2.png)
![Screenshot 2021-09-02 at 15 12 57](https://user-images.githubusercontent.com/42963845/131870087-69d00c63-a28c-48d6-931f-b6f446f643aa.png)

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-09-02 15:18 UTC, arnorhs approved these changes

2021-09-02 15:19 UTC, arnorhs requested changes

2021-09-02 15:19 UTC, arnorhs commented on libs/application/templates/driving-license/src/fields/ExamplePaymentPendingField.tsx
> +            <img src="/assets/images/company.svg" alt="Skrautmynd" />
The alt text should probably be in language strings

2021-09-06 09:48 UTC, arnorhs approved these changes

2021-09-06 10:02 UTC, jeremybarbet approved these changes
LGTM

2021-09-06 10:28 UTC, merged