chore(driving-license): Load-testing drivers's license components
island-is/island.is pull request #4997
Opened 2021-09-14 16:26 UTC by pshomov

# ...

We are simply using the feature-deployment

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-09-17 14:06 UTC, dabbeg commented on libs/api/domains/license-service/src/lib/licenseService.service.ts
> +    if (nationalId !== process.env.HI_I_AM_DAVID) {
:grin:

2021-09-17 14:32 UTC, sindrig requested changes

2021-09-17 14:32 UTC, sindrig commented on infra/src/feature-env.ts
> +        'List of comma separated Docker image names that have changed',
fix description

2021-09-17 14:32 UTC, sindrig commented on libs/api/domains/license-service/src/lib/licenseService.service.ts
> +    if (nationalId !== process.env.HI_I_AM_DAVID) {
HI DAVID I'M ERROR

2021-09-17 14:38 UTC, dabbeg commented on libs/api/domains/license-service/src/lib/licenseService.service.ts
> +    if (nationalId !== process.env.HI_I_AM_DAVID) {
HI SINDRI R U ERROR 2?

2022-02-11 09:24 UTC, Valur approved these changes

2023-06-26 08:49 UTC, closed without merging