feat(license-service): add pkpass service token to cache if possible
island-is/island.is pull request #5022
Opened 2021-09-16 11:23 UTC by osk

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-09-16 15:50 UTC, maranomynet requested changes

2021-09-16 15:50 UTC, maranomynet commented on libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
> +    const cached = await this.cacheManager?.get(CACHE_KEY)
```suggestion
    const cached = await this.cacheManager.get(CACHE_KEY)
```

It's already establised that `cacheManager` is defined

2021-09-16 15:50 UTC, maranomynet commented on libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
> +      return cached as string
```suggestion
      return cached
```

we've already establised that `typeof cached === 'string'` in the line above

2021-09-16 15:50 UTC, maranomynet commented on libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
> +    if (cached && typeof cached === 'string' && cached.length > 0) {
```suggestion
    if (cached && typeof cached === 'string') {
```

The length check is redundant since cached is known to be `true`y

2021-09-16 15:50 UTC, maranomynet commented on libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
> +      if (!isNaN(parsed) && parsed > 0) {
```suggestion
      if (parsed > 0) {
```

`parsed > 0` never evaluates to `true` if `parsed` is `NaN`

2021-09-16 15:50 UTC, maranomynet commented on libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
> +        Date.parse(expiry) - Date.now() - CACHE_TOKEN_EXPIRY_DELTA_IN_MS
```suggestion
        Date.parse(expiry).getTime() - Date.now() - CACHE_TOKEN_EXPIRY_DELTA_IN_MS
```

I prefer explicit `.getTime()` calls, over implicit `.valueOf()`

2021-09-16 15:50 UTC, maranomynet commented on libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
>      if (response.status === 1 && response.data?.ACCESS_TOKEN) {
```suggestion
    const token = response.data?.ACCESS_TOKEN
    if (response.status === 1 && token) {
```

2021-09-16 15:50 UTC, maranomynet commented on libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
> +      const token = response.data?.ACCESS_TOKEN
```suggestion
```

2021-09-16 15:57 UTC, maranomynet commented on libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
> +        Date.parse(expiry) - Date.now() - CACHE_TOKEN_EXPIRY_DELTA_IN_MS
my bad. Date.parse() returns a number.

2021-09-17 09:37 UTC, thordurhhh approved these changes

2021-09-17 10:03 UTC, maranomynet approved these changes

2021-09-17 10:09 UTC, merged