fix(ci): Force quotes in yaml [Take 2]
island-is/island.is pull request #5046
Opened 2021-09-20 09:18 UTC by sindrig

This reverts commit f72fe1d361678eeed28e0a6c6357fe7e87e72a12.

2021-09-20 12:06 UTC, eirikurn requested changes
There are a some more places calling `safe*` in the codebase, eg in the API Catalogue. 

Hopefully we'll find them when we upgrade `@types/js-yaml`, but might want to look through all imports/usage to be safe (not that much).

2021-09-20 12:06 UTC, eirikurn commented on package.json
> +    "js-yaml": "4.1.0",
Please upgrade `@types/js-yaml` as well.

2021-09-20 18:50 UTC, eirikurn approved these changes
Sweet!

2021-09-21 09:25 UTC, pshomov approved these changes
LGTM

2021-09-21 09:50 UTC, saevar43 approved these changes
LGTM

2021-09-21 09:50 UTC, arnorhs approved these changes

2021-09-21 10:24 UTC, merged