feat(judicial-system): Upload to Auður
island-is/island.is pull request #5076
Opened 2021-09-21 14:28 UTC by oddsson

# Upload to Auður

https://app.asana.com/0/1199153462262248/1200905978520084/f

## What

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-09-22 14:34 UTC, oddsson commented
In the video in the description, the first file name is really long and it doesn't look good. I've created a task for this in Asana because it's not a blocker for this PR.

2021-09-22 21:50 UTC, gudjong requested changes
One minor change request consideration.

2021-09-22 21:50 UTC, gudjong commented on apps/judicial-system/web/src/shared-components/CaseFileList/CaseFileList.tsx
> +                  CaseFileState.DELETED,
The server will never return DELETED files.

2021-09-22 21:50 UTC, gudjong commented on apps/judicial-system/web/src/shared-components/CaseFileList/CaseFileList.tsx
> +                  CaseFileState.DELETED,
Consider removing DELETED test here.

2021-09-23 12:12 UTC, gudjong approved these changes

2021-09-23 16:00 UTC, merged