chore(judicial-system): Change ruling email body for defenders and prosecutor
island-is/island.is pull request #5084
Opened 2021-09-22 15:47 UTC by oddsson

# Change ruling email body for defenders and prosecutor

https://app.asana.com/0/1199153462262248/1200978846073137/f

## What

Change ruling email body for defenders and prosecutor

## Why

This is more respectable 🧐

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-09-22 15:51 UTC, baldur-kolibri requested changes
Can this be managed under Contentful?

2021-09-22 21:56 UTC, gudjong approved these changes

2021-09-22 22:31 UTC, gudjong commented
> Can this be managed under Contentful?

Yes, but no email texts are in Contentful at this time. Perhaps, this should be a different task.

2021-09-23 09:21 UTC, baldur-kolibri approved these changes

2021-09-23 09:36 UTC, merged