feat(an): New review flow
island-is/island.is pull request #5232
Opened 2021-10-11 10:31 UTC by sigruntg

# New review flow

https://app.clickup.com/t/1f36kmz
https://app.clickup.com/t/1f36ktk
https://app.clickup.com/t/1f36m4r

## What

Updateing review to one page that switches between review, add documents and overview.

## Why

Specify why you need to achieve this

## Screenshots / Gifs

![image](https://user-images.githubusercontent.com/39527334/136775899-02a6bcf3-5222-4d6f-bb95-db4128cade17.png)
![image](https://user-images.githubusercontent.com/39527334/136775921-e8831a5e-4fb7-47ab-8889-4135c5cca989.png)
![image](https://user-images.githubusercontent.com/39527334/136775937-46d89c68-fcb6-46c6-81c0-4222f1385e1e.png)

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-10-12 15:41 UTC, Thorrik58 commented on libs/application/templates/accident-notification/src/lib/messages/thirdPartyComments.ts
> +        'Ef það eru einhverjar upplýsingar varðandi tilkynninguna sem þú vilt setja útá eða auka upplýsingar varðandi slysið sem þú vilt koma á framfæri þá er hægt að gera það hér að neðan.',
```suggestion
        'Ef það eru einhverjar upplýsingar varðandi tilkynninguna sem þú vilt setja útá eða auka upplýsingar varðandi slysið sem þú vilt koma á framfæri þá er hægt að gera það hér að neðan',
```

2021-10-12 15:44 UTC, Thorrik58 requested changes
Just some minor comments

2021-10-12 15:45 UTC, sigruntg commented on libs/application/templates/accident-notification/src/utils/getInjuredPersonInformation.spec.ts
> +      email: 'sigrun@sendiradid.is',
I'm always looking for new friends 🤓

2021-10-13 12:32 UTC, sigruntg commented on libs/application/templates/accident-notification/src/fields/InReviewSteps/index.tsx
> +  const showMissingDocumentsMessage = (answers: FormValue) => {
I don't think we need this anymore, I will only check if it has missing documents.

2021-10-13 12:47 UTC, sigruntg commented on libs/application/templates/accident-notification/src/fields/InReviewSteps/index.tsx
> +        !isRepresentativeOfCompanyOrInstitute(application.answers),
No, if you are not a representitive of company and the injured and if it was not home activity accident it should return false and you will not see this.

2021-10-13 16:46 UTC, merged