feat(financial-aid): Create my application endpoint and statuspage upgrade
island-is/island.is pull request #5250
Opened 2021-10-12 10:08 UTC by MargretFinnboga

# Create my application endpoint and status page upgrade

https://app.asana.com/0/1201097099198335/1201165297934591

## What

When fetching application checks where user is coming from and gives access to eventtype according to service. 
Upgraded the status pages sites, from all states
Created application provider, to fetch he current application once

## Why

Limiting the access to application events for the user looking at the status page 
provider so application survives the refresh and if there more pages coming allows us to have access to the application

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2021-10-12 12:58 UTC, Rikkiabb reviewed
Check it 💣

2021-10-12 12:58 UTC, Rikkiabb commented on apps/financial-aid/web-osk/pages/_app.tsx
> +                <MunicipalityProvider>
Does it make sense to join any providers? 

So we have a simpler hierarchy.

2021-10-12 12:58 UTC, Rikkiabb commented on apps/financial-aid/web-osk/src/components/ApplicationProvider/ApplicationProvider.tsx
> +}
Is this interface needed?

2021-10-12 12:58 UTC, Rikkiabb commented on apps/financial-aid/web-osk/src/components/ApplicationProvider/ApplicationProvider.tsx
> +  const storageKey = 'myCurrentApplication'
I would keep this const elsewhere, either in const or above the provider definition

2021-10-12 12:58 UTC, Rikkiabb commented on apps/financial-aid/web-osk/src/components/Status/Approved.tsx
> +  }
Should we rather, send in a boolean for this? Something like `IsStateActive`  ?

2021-10-12 12:58 UTC, Rikkiabb commented on apps/financial-aid/web-osk/src/components/ApplicationProvider/ApplicationProvider.tsx
> +  fetchError?: ApolloError
Should we call this error?

2021-10-13 13:23 UTC, Rikkiabb requested changes
Awesome PR ❤️‍🔥 Small stuff

2021-10-13 13:23 UTC, Rikkiabb commented on apps/financial-aid/backend/src/app/modules/application/application.controller.ts
> +      user,
Should findById take just service since it is not using anything else from user?

2021-10-13 13:23 UTC, Rikkiabb commented on apps/financial-aid/web-osk/pages/_app.tsx
> +            <AppProvider>
❤️

2021-10-13 13:23 UTC, Rikkiabb commented on apps/financial-aid/web-osk/src/components/Status/Approved.tsx
> +  isStateVisable: boolean
Isn't it `visible` not `visable` ?

2021-10-13 13:23 UTC, Rikkiabb commented on apps/financial-aid/web-osk/src/routes/status/FileUpload/fileUpload.tsx
> +    return
Is this return here needed?

2021-10-13 13:23 UTC, Rikkiabb commented on apps/financial-aid/web-osk/src/utils/useLogOut.ts
> +    sessionStorage.clear()
Nice

2021-10-13 16:17 UTC, MargretFinnboga commented on apps/financial-aid/web-osk/src/components/Status/Approved.tsx
> +  isStateVisable: boolean
🙃 🙃

2021-10-14 13:18 UTC, merged