fix(web): Search all on icon click
island-is/island.is pull request #5767
Opened 2021-11-25 22:14 UTC by albinagu

Bæta við að leitað sé í öllu efni þegar smellt er á stækkunarglerið

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-11-26 14:47 UTC, stjanilofts approved these changes

2021-11-29 10:45 UTC, siggifv requested changes
@albinagu 

I see a few things that should be addressed, some of which are demonstrated in the attached screen recording below:

1. The "Leita í öllu efni" option at the bottom of search results is no longer there.
2. The styling of the search results has been changed.
3. On initial load of the page, the loading indicator is active and animated for a brief second.
4. After typing in a search string, the loading indicator is shown and animated, but after the results have been loaded, the animation stop, but the icon is not changed back to the magnification glass.
5. When clicking on an item in the search results, the search string is replaced with the title of the selected option, no loading indication is show even though the page is in fact loading the selected page. After some wait the selected page is loaded.
6. After typing in a search string, clicking outside the input field (blur) and clicking it again (focus) the search results do not appear again; not until you make changes to the search string.

https://user-images.githubusercontent.com/1277384/143852886-9bff9d7d-4756-48ba-b373-d9c4fea41071.mp4

2022-01-06 14:43 UTC, siggifv commented
@albinagu 
As per discussions on Slack, the proposed changes to this PR have been approved and merged into this PR via PR #6160. These changes did address some of the points I mentioned above in my previous comment, all but points 5 and 6. However, this PR already contains good improvements and bug fixes that we should wrap up and deliver and not have points 5 and 6 blocking those, so I'm approving this PR.

2022-01-06 14:43 UTC, siggifv approved these changes

2022-01-06 15:06 UTC, merged