feat(judicial-system): Stop calling CaseQuery on every page and use Context instead
island-is/island.is pull request #5818
Opened 2021-11-30 14:08 UTC by oddsson

# Stop calling CaseQuery on every page and use Context instead

https://app.asana.com/0/1199153462262248/1201423192590376/f

## What

Stop calling CaseQuery on every page and use Context instead

## Why

- This way of getting cases is a lot more DRY
- It makes the app feel faster. This is because we used to wait until we got the case from the server before we rendered anything. Now we render a skeleton while we fetch the case. Because we are using context, we implement this once whereas we'd have to implement this in every step if we fetch cases on every step.  

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2021-12-01 11:00 UTC, gudjong requested changes
Some comments, mainly concerns about the possibility of infinite loops.

2021-12-01 11:42 UTC, oddsson commented on apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx
> +  }, [workingCase, updateCase, setWorkingCase, autofill, formatMessage])
This does not result in an infinite loop. This useEffect is run twice, once when the FormProvider sets workingCase as the default workingCase and once when setWorkingCase is called on line 161 in this file.

2021-12-01 11:46 UTC, oddsson commented on apps/judicial-system/web/src/routes/Court/InvestigationRequest/Confirmation/Confirmation.tsx
> +      {user && (
In this PR, we show a skeleton while we are fetching the case in for FormProvider. I think we should rather show the skeleton while we are fetching the user (or anything else we might fetch). Showing a skeleton over hiding everything makes the app feel snappier. But I agree, in another PR. I've created a task for that [here](https://app.asana.com/0/1199153462262248/1201445009348695/f)

2021-12-02 11:18 UTC, gudjong approved these changes

2021-12-02 11:53 UTC, merged