fix(icelandic-names-registry): a few tweaks
island-is/island.is pull request #5828
Opened 2021-12-01 11:17 UTC by stjanilofts

- Make GET name by id under `@Get('/id/:id')`
- Add pipe for making sure id is a number
- Add pipe for making sure string contains characters from Icelandic alphabet

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-12-08 14:24 UTC, albinagu approved these changes

2021-12-08 20:18 UTC, darrikonn requested changes

2021-12-08 20:18 UTC, darrikonn commented on apps/icelandic-names-registry/backend/src/app/modules/icelandic-name/icelandic-name.controller.ts
> +  @Get('id/:id')
Not sure this falls inline with the API design guide (notably the naming conventions).
This doesn't specify what resource you're fetching and isn't really a RESTful design.
I personally haven't used this API before, so I'm assuming this is fetching Icelandic names, thus the following would make more sense for URI structure:
```
api/icelandic-names-registry/names/:id
api/icelandic-names-registry/names?search=xxx
```

Also feels like initial-letter can be combined with search ... it's just a matter of skipping `%` in the database query.

2022-06-01 08:44 UTC, darrikonn approved these changes

2022-07-06 11:41 UTC, merged