fix(fa): Use our own scope for national registry
island-is/island.is pull request #5902
Opened 2021-12-07 15:33 UTC by Rikkiabb

# ...
https://app.asana.com/0/1201427499183230/1201472387205525

## What
Forking national registry to use our own scope.

## Why
We don't have the default scope that national registry uses

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Formatting passes locally with my changes
- [X] I have rebased against main before asking for a review

2021-12-07 16:19 UTC, saevarma requested changes

2021-12-07 16:19 UTC, saevarma commented on apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/nationalRegistryXRoad.resolver.ts
> +@Scopes('@skra.is/individuals')
You should use your GQL api scope `@samband.is/internal` here as the skra.is scope is intended for skra.is resources. And here you are protecting your gql query.

2021-12-07 21:24 UTC, saevarma approved these changes
LGTM

2021-12-08 09:30 UTC, MargretFinnboga approved these changes
💯

2021-12-08 12:59 UTC, merged