feat(island-ui): add new popover variant for filter
island-is/island.is pull request #6063
Opened 2021-12-21 13:36 UTC by stjanilofts

New popover variant for `Filter`. Better description coming soon...

## Screenshots / Gifs

Screenshots/gifs coming soon...

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-12-21 14:23 UTC, kksteini approved these changes
LGTM

2021-12-22 09:57 UTC, siggifv approved these changes
LGTM

2022-01-05 13:52 UTC, oddsson requested changes

2022-01-05 13:52 UTC, oddsson commented on libs/island-ui/core/src/lib/Filter/Filter.stories.tsx
> +      labelClearAll="Hreinsa allar síu"
```suggestion
      labelClearAll="Hreinsa allar síur"
```

2022-01-05 13:52 UTC, oddsson commented on libs/island-ui/core/src/lib/Filter/Filter.tsx
> +    <FilterContext.Provider value={{ variant }}>
Could you use the `useContext` hook here, like you do in libs/island-ui/core/src/lib/Filter/FilterMultiChoice/FilterMultiChoice.tsx

2022-01-05 14:33 UTC, oddsson approved these changes

2022-01-06 09:10 UTC, merged