feat(user-profile): Adding user device tokens admin and lib client
island-is/island.is pull request #6075
Opened 2021-12-22 08:26 UTC by rafnarnason

# ...

Attach a link to issue if relevant

## What

make devicetokens accessible internally via admin scoped endpoint and lib client

## Why

so the notifications system can read devicetokens for push notifications

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2021-12-22 13:25 UTC, eirikurn requested changes

2021-12-22 13:25 UTC, eirikurn commented on libs/clients/user-profile/src/lib/userProfileClient.module.ts
> +// import { exportedApis } from './apis'
Remove?

2021-12-22 13:25 UTC, eirikurn commented on libs/clients/user-profile/src/lib/apiConfiguration.ts
> +export const ApiConfiguration = {
Maybe `UserProfileApiProvider`?

2021-12-22 13:25 UTC, eirikurn commented on libs/clients/user-profile/README.md
> +      const currentAuth = convertTokenToAuth(clientAuthToken)
Example should either show CurrentUser object or #6057.

2021-12-22 13:25 UTC, eirikurn commented on apps/services/user-profile/src/openApi.ts
> +          [UserProfileScope.admin]: '',
Description?

2021-12-22 13:25 UTC, eirikurn commented on apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
> +export class UserTokenController {
Should move to separate file?

2021-12-22 13:25 UTC, eirikurn commented on apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
> +  @Get('userProfile/:nationalId/deviceToken')
API design guide: "/device-tokens"?

2021-12-22 15:37 UTC, eirikurn approved these changes
👍

2021-12-22 15:37 UTC, eirikurn commented on apps/services/user-profile/src/app/user-profile/userToken.controller.ts
> +
Strange that format doesn't catch whitespace like this 🤷

2021-12-28 08:12 UTC, disaerna approved these changes
Looks good to me 👍

2021-12-28 10:52 UTC, merged