feat(web): Organization english news items
island-is/island.is pull request #6128
Opened 2022-01-04 15:31 UTC by RunarVestmann

# Organization english news items

## What

Added pages for english news items

Made the showExternalLinks boolean field in the OrganizationWrapper optional since that was forgotten previously

Also made the sidebar reflect on what page you were since previously it only did so when the language was set to Icelandic

## Why

Previously if you clicked on an english news item you would get a 404 page not found error

## Screenshots / Gifs

Clicking on this news item now brings you to another page which shows you more, previously there was a 404 page
![image](https://user-images.githubusercontent.com/43557895/148082212-38acb924-acf1-430d-b6b5-f902b53d0e51.png)

![image](https://user-images.githubusercontent.com/43557895/148082250-4704c2a3-4f4f-40ca-b17d-6f17af128f2d.png)

A page for all news items was also added since it previously didn't exist for the english version of the site
![image](https://user-images.githubusercontent.com/43557895/148082360-8ca769ce-4e85-4730-b7c1-7e8971b50e5a.png)

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-01-04 16:12 UTC, siggifv requested changes

2022-01-04 16:12 UTC, siggifv commented on apps/web/screens/Organization/Services.tsx
> +      namespace={namespace}
This will not be needed, as this parameter is being removed in PR #6129

2022-01-04 16:12 UTC, siggifv commented on apps/web/screens/Organization/SubPage.tsx
> +      namespace={namespace}
Same here, this will not be needed as this parameter is being removed in PR #6129

2022-01-04 16:37 UTC, siggifv approved these changes

2022-01-04 16:38 UTC, siggifv approved these changes

2022-01-05 10:16 UTC, kksteini approved these changes
LGTM

2022-01-05 16:37 UTC, merged