fix(personal-representative): Gitbook and docker setup update
island-is/island.is pull request #6321
Opened 2022-01-19 15:47 UTC by FridrikMProgramm

Gitbook update
Also adding dockerizing to workspace settings

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-01-19 16:27 UTC, saevarma requested changes
This PR includes 239 commits, I think there is something strange with the history of this branch?

2022-01-19 16:27 UTC, saevarma commented on apps/services/personal-representative-public/README.md
> +http://localhost:3378/swagger/#/default
```suggestion
http://localhost:3378/swagger
```

2022-01-19 16:27 UTC, saevarma commented on apps/services/personal-representative/README.md
> +http://localhost:3378/swagger/#/default
```suggestion
http://localhost:3378/swagger
```

2022-01-20 08:32 UTC, FridrikMProgramm commented
> This PR includes 239 commits, I think there is something strange with the history of this branch?
I reused a deleted PR, might have something to do with it. But it only seems to affect the "history" not the outcome.

2022-01-20 08:49 UTC, fjandakornid approved these changes
LGTM

2022-01-20 11:13 UTC, closed without merging