feat(service-portal): onboard feature testing
island-is/island.is pull request #6376
Opened 2022-01-25 13:22 UTC by thordurhhh

# WIP ONBOARD FEATURE TEST.

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-02-09 10:09 UTC, disaerna commented on apps/services/user-profile/src/app/user-profile/verification.service.ts
> +    // console.log('emailCode', emailCode)
cleanup?

2022-02-09 10:11 UTC, disaerna commented on apps/services/user-profile/src/app/user-profile/verification.service.ts
> +        html: `Þú hefur skráð netfangið þitt á Mínum síðum á Ísland.is. Vinsamlegast staðfestu
Er þetta þýtt einhverstaðar ? 🤔

2022-02-09 10:37 UTC, kksteini commented on libs/api/domains/user-profile/src/lib/userProfile.service.ts
> +        canNudge: islyklarData?.canNudge,
`canNudge` was removed from the islykill.service in this pull request. Is this for backwards compatibility or something else?

2022-02-09 10:51 UTC, kksteini commented on libs/api/domains/user-profile/src/lib/userProfile.service.ts
> +        canNudge: islyklarData?.canNudge,
Though I am seeing at as optional in some inputs elsewhere, is this not being returned?

2022-02-09 11:24 UTC, kksteini commented on libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx
> +                  {!verifiCationLoading &&
strange camelcasing :sweat_smile:

2022-02-09 12:46 UTC, kksteini requested changes

2022-02-09 12:56 UTC, Valur commented on libs/service-portal/settings/personal-information/src/utils/outOfDate.ts
> +    (emptyMail && diffOutOfDate) || (emptyMobile && diffOutOfDate)
Shorter version: (emptyMail || emptyMobile) && diffOutOfDate

2022-02-09 12:57 UTC, Valur commented on libs/service-portal/settings/personal-information/src/utils/outOfDate.ts
> +  const dateNow = new Date(Date.now())
"Date.now()" here is unnecessary

2022-02-10 09:03 UTC, disaerna commented on libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx
> +                  {!verifiCationLoading &&
Fixed

2022-02-10 09:04 UTC, disaerna commented on libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Phone.tsx
> +                <button type="submit" disabled={verificationValid}>
I agree - it doesnt work without it though 🤭 . I'll write this down as to reconsider on refactor week ?

2022-02-10 09:04 UTC, disaerna commented on libs/service-portal/settings/personal-information/src/lib/messages.ts
> +    defaultMessage: `Vinsamlegast farðu vel yfir allar neðangreindarupplýsingar, gangtu í
Done

2022-02-10 09:04 UTC, disaerna commented on libs/service-portal/settings/personal-information/src/utils/outOfDate.ts
> +    (emptyMail && diffOutOfDate) || (emptyMobile && diffOutOfDate)
Done

2022-02-10 09:04 UTC, disaerna commented on libs/service-portal/settings/personal-information/src/utils/outOfDate.ts
> +  const dateNow = new Date(Date.now())
Done

2022-02-10 09:04 UTC, disaerna approved these changes

2022-02-10 15:11 UTC, disaerna commented on libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx
> +                  {!verifiCationLoading &&
@kksteini - can you re-review? 🙏

2022-02-11 11:35 UTC, disaerna commented on libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Phone.tsx
> +                <button type="submit" disabled={verificationValid}>
This is because the button is of type text and then in island-ui it is rendered as div, and that's why type=submit doesnt work 😞

2022-02-11 13:39 UTC, kksteini approved these changes

2022-02-11 15:13 UTC, merged