fix(judicial-system): fix prefill for ruling input
island-is/island.is pull request #6805
Opened 2022-03-08 13:14 UTC by Arnarkari93

# ...

[Asana task](Attach a link to issue if relevant)

## What

- Prefill input when the judge is drafting the ruling 

## Why

- It is prefilled later in the flow with the name of the judge

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-03-08 13:29 UTC, Arnarkari93 commented on apps/judicial-system/web/src/components/RulingInput/RulingInput.tsx
> -    if (isCaseUpToDate) {
isCaseUpToDate is set to false after one sec. Therefore, it is never set to `true` in modals.

2022-03-08 13:54 UTC, oddsson requested changes
I agree with you, `isCaseUpToDate` will never be true in modals. However the `rulingInput` component is not only used in this modal, it's used on the ruling pages as well, and on those pages we need the `isCaseUpToDate` functionality. 

Maybe we should move the autofill out of the rulingInput component and onto the overview page? That way, the `isCaseUpToDate` functionality continues to work. What do you think?

2022-03-08 14:54 UTC, Arnarkari93 commented
> I agree with you, `isCaseUpToDate` will never be true in modals. However the `rulingInput` component is not only used in this modal, it's used on the ruling pages as well, and on those pages we need the `isCaseUpToDate` functionality.
>   
> Maybe we should move the autofill out of the rulingInput component and onto the overview page? That way, the `isCaseUpToDate` functionality continues to work. What do you think?

I was thinking if we should rethink the autofill logic. Feels a bit hacky to control with a state that is reset with a `setTimeout`. I was thinking we could write a custom hook that we use for each field that needs to be autofill and make sure there it is only updated when we want it to.

2022-03-09 11:02 UTC, Arnarkari93 commented
Close in favour of #6817

2022-03-09 11:02 UTC, closed without merging