refactor(judicical-system): remove defenderIsSpokePerson
island-is/island.is pull request #6882
Opened 2022-03-15 21:38 UTC by Arnarkari93

# remove defenderIsSpokeperson

Attach a link to issue if relevant
[Asana task](https://app.asana.com/0/1199153462262248/1201813931659682/f)

## What

- Remove `defenderIsSpokeperson` from the project

## Why

- All logic should be depenant on the session arrangement

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-03-17 09:11 UTC, oddsson approved these changes

2022-03-17 16:02 UTC, gudjong requested changes

2022-03-17 16:40 UTC, Arnarkari93 commented on apps/judicial-system/backend/src/app/formatters/requestPdf.ts
> +        theCase.sessionArrangements ===
Yes, good catch!

2022-03-17 16:45 UTC, Arnarkari93 commented on apps/judicial-system/backend/src/app/formatters/requestPdf.ts
> +        theCase.sessionArrangements ===
fixed in: 67114ebda66e66b9536ec2c2fe5a9298758d1d55

2022-03-18 07:55 UTC, gudjong approved these changes

2022-03-18 13:19 UTC, merged