feat(fa): Creating a printable application with files
island-is/island.is pull request #6905
Opened 2022-03-17 15:11 UTC by MargretFinnboga

# Creating a printable application with files

https://app.asana.com/0/1201927126329736/1201445348663381

## What

- Make a page where application is printable 
- Fetch all image and display them 
- Fetch all pdfs and display them as well 
- Update pdf viewer when you want to display whole pdf and as canvas 

## Why

- Requested from staff in municipality 
- To use pdf viewer in more ways

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

application
![Screenshot 2022-03-22 at 10 14 48](https://user-images.githubusercontent.com/62568905/159458211-04891f45-be95-4337-a66d-0f6333ded13d.png)

printable view

![Screenshot 2022-03-22 at 10 15 10](https://user-images.githubusercontent.com/62568905/159458232-bbd8b906-116e-40dc-85a0-239b91e6a71e.png)

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-03-17 16:07 UTC, addi requested changes

2022-03-17 16:07 UTC, addi commented on apps/financial-aid/web-veita/src/components/PrintableFiles/PrintableFiles.tsx
> +  if (allIPdfs.length === files.length) {
Það er hægt að gera betri error logic in þetta. Þetta er frekar weird.

2022-03-17 16:07 UTC, addi commented on apps/financial-aid/web-veita/src/components/PrintableFiles/PrintableFiles.tsx
> +    const { data } = useQuery(GetSignedUrlQuery, {
Já spurning um að gera endapunkt sem skilar signed url yfir allar skrár.

2022-03-17 16:07 UTC, addi commented on apps/financial-aid/web-veita/src/components/PrintableFiles/PrintableFiles.tsx
> +  const allIPdfs: string[] = []
Eru ekki bara pdf, eru ekki líka myndir hérna.

2022-03-17 16:07 UTC, addi commented on apps/financial-aid/web-veita/src/routes/Application/application.tsx
>    const [isLoading, setIsLoading] = useState(false)
Þarftu þennan? er ekki nóg að hafa loading sem er þarna fyrir neðan?

2022-03-21 11:07 UTC, MargretFinnboga commented on apps/financial-aid/web-veita/src/routes/Application/application.tsx
>    const [isLoading, setIsLoading] = useState(false)
Nei þarf þennan þegar application er uppfært 😇

2022-03-21 11:09 UTC, MargretFinnboga commented on apps/financial-aid/web-veita/src/routes/Application/application.tsx
>    const [isLoading, setIsLoading] = useState(false)
En kannski óþarfi þarna þar sem ekki er hægt að ýta á takka 🙃

2022-03-21 13:06 UTC, MargretFinnboga commented on libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
> +              {Array.from(new Array(numPages), (el, index) => (
Array.from(new Array(numPages), þá þetta eða tjékið?

2022-03-21 13:07 UTC, MargretFinnboga commented on apps/financial-aid/web-veita/src/components/AdminLayout/AdminLayout.tsx
> +  const printPage = router.pathname.includes('print')
alvöru route hvað meinaru 🤓 ?

2022-03-22 11:13 UTC, Arnarkari93 approved these changes
LGTM from the `island-ui` perspective

2022-03-22 13:53 UTC, davidpxn approved these changes
This looks good to me! 👏

2022-03-22 17:33 UTC, merged