chore: upgrading ioredis dependency in the hope of getting rid of some annoying errors
island-is/island.is pull request #6949
Opened 2022-03-23 10:37 UTC by pshomov

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-03-23 16:16 UTC, eirikurn requested changes

2022-03-24 12:23 UTC, pshomov commented on package.json
> +    "ioredis": "4.28.5"
I added it to avoid pulling two versions of the dependency. Do we not want that?

2022-03-24 16:55 UTC, eirikurn commented on package.json
> +    "ioredis": "4.28.5"
It is "one" way to deduplicate dependencies but it's a very agressive tool which should be avoided whenever possible to not cause unexpected issues.

In this point the dependency is already deduplicated and matches all semver ranges so the resolution is safe to remove.

2022-03-24 18:02 UTC, pshomov commented on package.json
> +    "ioredis": "4.28.5"
Reverting this change. I swear I got two packages in my yarn.lock file locally before I added this resolution thing. 🤷🏻‍♂️

2022-03-24 18:15 UTC, eirikurn approved these changes

2022-03-24 19:23 UTC, eirikurn commented on package.json
> +    "ioredis": "4.28.5"
Yeah. That happens sometimes even though the new dependency matches all the version ranges. 

Resolutions is one way to fix it, but best to remove it afterwards unless it's really neccessary (eg to force sub-dependencies outside their version range)

2022-03-25 06:45 UTC, merged