docs(auth): Add IAS technical documentation to handbook
island-is/island.is pull request #6950
Opened 2022-03-23 10:44 UTC by eirikurn

## What

Technical documentation about the new IAS service.

## Why

To explain what IAS is all about to third parties.

## Screenshots / Gifs

[Link to documentation](https://github.com/island-is/island.is/blob/53798ac3a13ede2ad8509e25b5fc1a49da80d8b8/handbook/technical-overview/auth/README.md)

2022-03-23 23:21 UTC, hrefnalind commented on handbook/technical-overview/auth/delegations.md
> +When a user signs into a client which supports delegations, IAS prompts the user with a choice to authenticate without a delegation, or authenticate with a specific delegation.
should we present the Mínar síður way as an option ?

2022-03-23 23:21 UTC, hrefnalind commented on handbook/technical-overview/auth/environments.md
> +The staging environment SHOULD be used when developing and testing an IAS integration.
Where do I get test data ? (Lets discuss)

2022-03-25 10:39 UTC, johannasvovu commented
Looks good to me, very detailed!

2022-03-28 13:09 UTC, hrefnalind commented on handbook/technical-overview/auth/environments.md
> +The staging environment SHOULD be used when developing and testing an IAS integration.
Users can get test data by sending request to island@island.is

2022-03-28 23:06 UTC, saevarma requested changes
Great documentation!

2022-03-31 19:51 UTC, eirikurn commented on handbook/technical-overview/auth/scopes-and-tokens.md
> +- `idp` - The identity provider used to authenticate the user. Can contain values:
I'll update the docs when we've decided on a plan. After discussing electronic signatures, it might be nice to also have this in a separate claim.

2022-04-01 11:45 UTC, valurefugl commented on handbook/technical-overview/auth/integration-guidance.md
> +- [IdentityModel.AspNetCore](https://github.com/IdentityModel/IdentityModel.AspNetCore) - OIDC implementation for .NET.
For .NET think we should recommend the Microsoft.AspNetCore.Authentication.OpenIdConnect package, see https://docs.microsoft.com/en-us/dotnet/architecture/microservices/secure-net-microservices-web-applications/#authenticate-with-an-openid-connect-or-oauth-20-identity-provider

2022-04-01 11:48 UTC, valurefugl commented on handbook/technical-overview/auth/integration-guidance.md
> +- [ASP.NET Core Authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-6.0) - JWT validation for .NET.
Maybe link to this description for the Microsoft.AspNetCore.Authentication.JwtBearer package, https://docs.microsoft.com/en-us/dotnet/architecture/microservices/secure-net-microservices-web-applications/#consume-security-tokens

2022-04-01 12:58 UTC, hrefnalind approved these changes

2022-04-04 22:51 UTC, saevarma approved these changes
👏👏

2022-04-04 23:40 UTC, merged