fix(application-system): Use UserProfileLocale from service-portal in application
island-is/island.is pull request #7251
Opened 2022-04-27 14:25 UTC by Thorrik58

# Use UserProfileLocale from service-portal in application

Attach a link to issue if relevant

## What

Use UserProfileLocale from service-portal in application and place that component into the shared react components.

## Why

Persisting locale through refreshes and between browsers.
Shared component used to avoid duplication of code.

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-04-27 14:32 UTC, thordurhhh approved these changes
Service portal looking good 👍

2022-04-27 14:46 UTC, saevarma requested changes
The moved `UserProfileLocale` still depends on the query from `service-portal`. The `@island.is/shared/components` shouldn't depend on `service-portal`.

2022-04-27 15:29 UTC, saevarma requested changes

2022-04-28 10:14 UTC, obmagnusson approved these changes

2022-04-28 16:59 UTC, Thorrik58 commented on libs/shared/components/src/auth/UserMenu/UserProfileLocale.tsx
> +  const [getUserProfile, { data }] = useLazyQuery<Query>(GET_FULL_USER_PROFILE)
Fixed and some more tweaks

2022-04-29 09:30 UTC, merged