chore: Updating client id references from ids-admin to @island.is/auth-admin-web where it is used
island-is/island.is pull request #7295
Opened 2022-05-02 12:18 UTC by johannasvovu

# ...

Attach a link to issue if relevant

## What

Renaming references from ids-admin to @island.is/auth-admin-web due to renaming of the client

## Why

Clients should now follow a naming convention that ids-admin does not satisfy.

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-05-03 14:41 UTC, saevarma requested changes

2022-05-03 14:41 UTC, saevarma commented on libs/auth-api-lib/seeders/local/003-ids-admin.client.js
> +  client_claims_prefix: '@island.is/auth-admin-webn_',
```suggestion
  client_claims_prefix: '@island.is/auth-admin-web_',
```

2022-05-05 08:28 UTC, valurefugl approved these changes

2022-05-05 10:07 UTC, saevarma approved these changes
LGTM. Just remember that the update of the client secret must follow as closely to the release of this as possible.

2022-05-05 11:01 UTC, merged