feat(service-portal): Inbox UI updates
island-is/island.is pull request #7333
Opened 2022-05-05 14:29 UTC by thordurhhh

## What

Update inbox UI.

* Add filters for unread
* Add sorting

## Why

Added filter/sorting value for users.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-06-13 16:43 UTC, disaerna requested changes
Minor comments, otherwise very very nice 💯 🥇

2022-06-13 16:43 UTC, disaerna commented on libs/service-portal/documents/src/screens/Overview/Overview.tsx
> +  console.log('categories', categories)
👀 👀 👀

2022-06-13 16:43 UTC, disaerna commented on libs/service-portal/documents/src/screens/Overview/Overview.tsx
> +            labelClear={'Hreinsa síu'}
Tranlsations missing

2022-06-13 16:43 UTC, disaerna commented on libs/service-portal/documents/src/screens/Overview/Overview.tsx
> +            labelClear={'Hreinsa síu'}
... on all labels for <Filter

2022-06-13 16:43 UTC, disaerna commented on libs/service-portal/documents/src/screens/Overview/Overview.tsx
> +                  label="Sýna einungis ólesið"
Translations

2022-06-13 16:43 UTC, disaerna commented on libs/service-portal/documents/src/screens/Overview/Overview.tsx
> +              labelClear="Hreinsa val"
Translations

2022-06-13 16:43 UTC, disaerna commented on libs/service-portal/documents/src/screens/Overview/Overview.tsx
> +                    label: 'Flokkur',
Translations

2022-06-13 16:43 UTC, disaerna commented on libs/service-portal/documents/src/screens/Overview/Overview.tsx
> +                    label="Dagsetningar"
Translations

2022-06-13 21:14 UTC, thordurhhh commented on libs/service-portal/documents/src/screens/Overview/Overview.tsx
> +  return direction === 'asc' ? 'desc' : 'asc'
Yes it is. It's actually taking the current direction in and reversing.
I will make it a bit clearer to read though. 😅

2022-06-14 08:06 UTC, disaerna approved these changes
👍  I like

2022-06-14 08:10 UTC, merged