refactor: replace ed card with action card + translations
island-is/island.is pull request #7396
Opened 2022-05-12 10:07 UTC by disaerna

# Service portal - Fix broken education cards

## What

Fix broken self made action cards and replace it with action card from ui core library.

## Why
Cuz it's broken 😞 

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-05-12 10:11 UTC, darrikonn requested changes
Nice work.

2022-05-12 10:11 UTC, darrikonn commented on libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx
> +                    id: 'sp.education-career:send-file',
id should be education-license.

2022-05-12 10:11 UTC, darrikonn commented on libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx
> +                      id: 'sp.education-career:download',
ditto on all ids.

2022-05-12 10:19 UTC, disaerna commented on libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx
> +                    id: 'sp.education-career:send-file',
✅

2022-05-12 10:19 UTC, disaerna commented on libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx
> +                      id: 'sp.education-career:download',
✅

2022-05-16 13:08 UTC, kksteini commented on libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx
> +                        'Athugið að niðurhalslinkurinn rennur út eftir',
Er ekki betri íslenska: `niðurhalshlekkurinn`.

2022-05-16 13:08 UTC, kksteini commented on libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx
> +                      defaultMessage: 'Niðurhalslinkurinn er útrunninn.',
Sama hér

2022-05-16 13:08 UTC, kksteini approved these changes

2022-05-16 13:28 UTC, merged