refactor(core): Refactor withHealthchecks into lib and reuse in next apps.
island-is/island.is pull request #7449
Opened 2022-05-17 14:39 UTC by saevarma

## What

auth-admin-web was using `withHealthchecks` from the web project, creating dependency.
Also each next app has copy-paste of the `withHealthchecks` wrapper and the config.

This PR refactors this into a new `next/health` library.

## Why

- Decouple unwanted dependency.
- Simplify `withHealthchecks` setup.

## Screenshots / Gifs

N/A

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-05-18 14:11 UTC, eirikurn approved these changes
Sooo much nicer! Great job! 💯

2022-05-18 14:11 UTC, eirikurn commented on workspace.json
> -            "assets": ["apps/web/next-modules"]
Such good feelings :D

2022-05-18 14:49 UTC, saevarma commented on libs/infra-next-server/src/lib/health.ts
> +        : externalEndpointDependencies
Yes that is the reason. Passing in the nextjs config is a great idea to simplify those function.

Ahh ofc we shouldn't be calling it in the request handler, will move it.

2022-05-18 15:36 UTC, Snojo approved these changes
LGTM

2022-05-19 09:31 UTC, essgje approved these changes
left

2022-05-19 11:00 UTC, kristofer-lp8f requested changes
Looks good.

I'll approve upon comment resolution.

2022-05-19 13:06 UTC, davidpxn approved these changes
LGTM

2022-05-19 13:11 UTC, saevarma commented on libs/infra-next-server/src/lib/health.ts
> +    e.g the web app should render the error page for users if the api goes offline the web app should not go offline
Added missing comma and period.

2022-05-19 16:37 UTC, merged