feat(regulations): Regulations/UI addons
island-is/island.is pull request #7474
Opened 2022-05-19 14:30 UTC by Valur

## What

Add ui tweaks used in regulations admin and update some related code

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-05-20 11:34 UTC, thordurhhh approved these changes
👍

2022-05-24 12:59 UTC, Arnarkari93 requested changes

2022-05-24 12:59 UTC, Arnarkari93 commented on libs/island-ui/core/src/lib/Tag/Tag.tsx
> +        {renderCloseIcon && <Icon icon="close" className={styles.closeIcon} />}
I think this should not be implemented in `island-ui` until the designs in Figma have been updated. If this should be added we need to account for accessibility.

2022-05-24 13:05 UTC, Arnarkari93 commented on libs/island-ui/core/src/lib/Tag/Tag.tsx
> +        {renderCloseIcon && <Icon icon="close" className={styles.closeIcon} />}
I think we should instead add a close icon by allowing the user to inject a custom icon instead—that way we allow for more flexibility for different use-cases.

2022-05-30 12:59 UTC, saevarma reviewed
Why does this PR include the `package.json` changes?

2022-06-21 14:47 UTC, closed without merging