feat(j-s): remove feature flag for modify ruling
island-is/island.is pull request #7650
Opened 2022-06-07 13:27 UTC by Arnarkari93

[Asana - Taka út feature hiding í staging og prod](https://app.asana.com/0/0/1202394369866929/f)
## What

Remove feature flag for modify ruling.

## Why

Ready for testing

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-06-08 09:08 UTC, Arnarkari93 commented on apps/judicial-system/api/infra/judicial-system-api.ts
> -        prod: 'MODIFY_RULING',
We have been working on a feature called modify ruling for a couple of weeks. Now we are ready to release it to prod. This PR is just removing the feature flag.

2022-06-09 09:33 UTC, oddsson requested changes
Variables `Feature` and `features` in apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx are unused. Please remove them

2022-06-09 10:31 UTC, oddsson approved these changes

2022-06-13 08:47 UTC, gudjong approved these changes

2022-06-13 08:47 UTC, gudjong commented on apps/judicial-system/api/infra/judicial-system-api.ts
> -        prod: 'MODIFY_RULING',
This is correct. We have been using this way to hide features on the client side almost from the beginning (of time) :)

2022-06-13 10:04 UTC, merged