Feat/parental leave add orginisation reviewer
island-is/island.is pull request #7696
Opened 2022-06-10 10:13 UTC by qdd1

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-06-10 10:41 UTC, karenbjorg approved these changes
for now LGTM!

2022-06-10 12:35 UTC, peturgq approved these changes
Looks good to me, without knowing fully if ParentalLeaveTemplate has access to the env vars exposed in application-system-form.

2022-06-10 13:01 UTC, obmagnusson requested changes
Looks good minor comments

2022-06-10 13:01 UTC, obmagnusson commented on libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
> +        // TODO: enable for user to do changes after application got APPROVE from VMST?
Should this not be addressed before merging for main? As everything going on main should be ready for production.

2022-06-13 10:32 UTC, obmagnusson requested changes

2022-06-13 10:32 UTC, obmagnusson commented on libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
> +      // TODO: rewrite when there is a way to test VMST ID
You should just be able to rewrite the process env for VMST_ID like so:
`process.env.VMST_ID = createNationalId('company')`

2022-06-13 11:21 UTC, obmagnusson requested changes

2022-06-14 14:29 UTC, merged