j s/fetch parent case files
island-is/island.is pull request #7739
Opened 2022-06-14 15:42 UTC by Arnarkari93

[Asana - Framlenging - gögn send dómnum í fyrra máli](https://app.asana.com/0/1199153462262248/1202037182089588/f)
## What

### Island-ui
-  make onRemoveClick optional

### Judicial-system
- show files of parent case
- add tests for displaying files of parent case
- move CaseFilesForm.tsx to CaseFiles.tsx
- move StepFiveForm.tsx to StepFive.tsx

## Why

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-06-14 15:45 UTC, Arnarkari93 commented on apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFive.tsx
> +        />
This is what I am adding

2022-06-14 16:45 UTC, gudjong requested changes
This looks good but `caseFiles` is missing from the `gql` query used by `FormProvider`.

2022-06-15 09:54 UTC, oddsson commented on apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/caseFiles.spec.ts
> +  it.only('should list of files for parent case', () => {
```suggestion
  it('should list of files for parent case', () => {
```

2022-06-15 09:54 UTC, oddsson commented on apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/caseFiles.spec.ts
> +  it.only('should list of files for parent case', () => {
```suggestion
  it('should list of files for parent case', () => {
```

2022-06-15 09:56 UTC, oddsson commented on apps/judicial-system/web/messages/InvestigationCases/Prosecutor/caseFiles.ts
> +          'judicial.system.investigation_cases:case_files.parentCaseFiles.heading',
We usually write the ids in_this_format. Please consider changing parentCaseFiles to parent_case_files

2022-06-15 09:56 UTC, oddsson commented on apps/judicial-system/web/messages/RestrictionCases/Prosecutor/caseFiles.ts
> +          'judicial.system.restriction_cases:case_files.parentCaseFiles.heading',
Same ☝️

2022-06-15 09:59 UTC, oddsson requested changes
Couple of things...

2022-06-16 08:55 UTC, oddsson approved these changes

2022-06-21 08:46 UTC, gudjong approved these changes

2022-06-21 09:34 UTC, merged