first draft
island-is/island.is pull request #7744
Opened 2022-06-14 18:38 UTC by Thorrik58

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-06-15 10:04 UTC, obmagnusson requested changes

2022-06-15 10:04 UTC, obmagnusson commented on libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
> +      return [Roles.ASSIGNEE, Roles.APPLICANT]
What happens when both these roles are assigned to one state?

2022-06-15 14:45 UTC, obmagnusson approved these changes

2022-06-21 10:14 UTC, saevarma requested changes

2022-06-21 10:14 UTC, saevarma commented on libs/testing/fixtures/src/lib/application.ts
> +
I think we should create a new type libs for application (libs/application/types) and move the types so we are not duplicating the Application and Template interface here.

2022-07-14 12:10 UTC, Thorrik58 commented
Build issues, recreated in https://github.com/island-is/island.is/pull/8048

2022-07-14 12:10 UTC, closed without merging