chore(application-login-service): Implement new company search in login service
island-is/island.is pull request #7766
Opened 2022-06-15 13:33 UTC by egill15

# Company search in login service

[https://app.clickup.com/t/2fkekvu](https://app.clickup.com/t/2fkekvu)
## What
Make the old company search code obsolete by implementing the new company search feature into the application.

## Why
Better code practice to use reusable functions. And it keeps things from being bloated.

## Screenshots / Gifs

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-06-15 14:48 UTC, saevarma requested changes

2022-06-15 14:48 UTC, saevarma commented on libs/application/templates/login-service/src/fields/IsatInvalid/IsatInvalid.tsx
> +      <GridColumn span={['1/1', '1/1', '1/1']} paddingTop={2}>
`span` accepts a single value and as the value is always the same you can do instead
```suggestion
      <GridColumn span='1/1' paddingTop={2}>
```

2022-06-15 14:48 UTC, saevarma commented on libs/application/templates/login-service/src/shared/types.ts
> +}
This type is duplicated here and in the `CompanySearchFromField` we should try to reuse the type.

2022-06-15 14:48 UTC, saevarma commented on libs/shared/form-fields/src/lib/CompanySearchController/CompanySearchController.tsx
> +    })
This can be simplified to
```suggestion
    const filteredCompany = companies.filter((company) => company.nationalId === nationalId )
```

2022-06-15 14:48 UTC, saevarma commented on libs/shared/form-fields/src/lib/CompanySearchController/CompanySearchController.tsx
> +    const companies: Array<any> = data?.companyRegistryCompanies?.data ?? []
You could let gql generate typed hooks for the query to get typed responses.

2022-06-15 14:48 UTC, saevarma commented on libs/shared/form-fields/src/lib/CompanySearchController/CompanySearchController.tsx
> +  const getIsatNumbers = (nationalId: string) => {
The function name indicates return of string array of ISAT numbers, but it only returns a single string with the main ISAT number
```suggestion
  const getIsatNumber = (nationalId: string) => {
```

2022-06-15 14:48 UTC, saevarma commented on libs/shared/form-fields/src/lib/CompanySearchController/CompanySearchController.tsx
> +  }
The search for the main ISAT can be improved to return when you find it
```suggestion
    for (let v of vats) {
      if (!v.dateOfDeregistration) {
        const classification = v.classification.find(c => c.type === 'Aðal')
        if (classification) {
          return `${c.number} - ${c.name}`
        }
      }
    }
    return ''
  }
```

2022-06-16 09:16 UTC, darrikonn requested changes
Can you clean up unused variables that this PR introduces?

2022-06-16 09:21 UTC, darrikonn requested changes

2022-06-16 09:21 UTC, darrikonn commented on libs/shared/form-fields/codegen.yml
> +schema:
IMO: It does not make sense to add a codegen here. This is a shared lib, used by all applications, and it should not have any graphql fields.

2022-06-16 09:21 UTC, darrikonn commented on libs/shared/form-fields/src/lib/CompanySearchController/CompanySearchController.tsx
>  import { AsyncSearch, Box, AlertMessage } from '@island.is/island-ui/core'
This component is probably the root issue. It should not be in this library, since it contains side effects that around bound to all applications.

2022-06-16 09:21 UTC, darrikonn commented on libs/shared/form-fields/src/lib/CompanySearchController/companySearchController.graphql.ts
> +import { gql } from '@apollo/client'
ditto

2022-06-16 13:29 UTC, darrikonn approved these changes
Approved, but can be improved by moving the isat logic to the api in a field resolver

2022-06-16 13:29 UTC, darrikonn commented on libs/application/ui-components/src/components/CompanySearchController/CompanySearchController.tsx
> +          return `${c.number} - ${c.name}`
This looks like the job of a field resolver that should be handled in the api.

2022-06-20 09:07 UTC, saevarma approved these changes
LGTM, but please consider Darri's recommendation on improvement.

2022-06-20 14:27 UTC, merged