wip
island-is/island.is pull request #7997
Opened 2022-07-06 09:41 UTC by disaerna

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-08-18 09:41 UTC, thordurhhh commented on libs/api/domains/documents/src/lib/document.service.ts
> +  async listDocuments(
We might want to publish these functions as version2 and keep the others in, while the app still uses them so we don't catch them by surprise when we change the responses. 😃

2022-08-18 10:04 UTC, thordurhhh requested changes
This is nice!
Only request for change I see is for a [second version of the document service](https://github.com/island-is/island.is/pull/7997/files#r948904425)

2022-08-22 10:09 UTC, thordurhhh approved these changes

2022-08-22 11:05 UTC, oddsson approved these changes

2022-08-22 12:32 UTC, merged