feat(web): Add RSS news feed
island-is/island.is pull request #8076
Opened 2022-07-29 10:20 UTC by Ingimarsson

# Add RSS news feed

## What

Add an RSS feed under `/rss.xml` that takes in query parameters `tag` and `lang`.

## Why

We currently need this for some organizations, to configure automatic mailing lists in Mailchimp for their news.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-07-29 13:44 UTC, kristofer-lp8f requested changes
I like the change. Nice i18n.

I'm not familiar with RSS internals, so these suggestions/change requests might not apply.

2022-07-29 13:44 UTC, kristofer-lp8f commented on apps/web/pages/api/rss/index.ts
> +</rss>`
Can you break down this nested templating? I would also like to see to see a templated base URL for development.

2022-07-29 14:51 UTC, Ingimarsson commented on apps/web/pages/api/rss/index.ts
> +        size: 25,
I have not seen that with RSS feeds on other sites, maybe we can skip it for now :)

2022-08-02 14:14 UTC, kristofer-lp8f approved these changes
Good adjustments and PR.

Minor comments/possible improvements, but non-blocking. Removed auto-merge and approving so you can address these comments at your own discretion.

2022-08-02 14:14 UTC, kristofer-lp8f commented on apps/web/pages/api/rss/index.ts
> +      : 'https://beta.dev01.devland.is'
This should allow any host/proxy:
```suggestion
  const host: string = req.headers.host
  const protocol = `http${host.startsWith('localhost') ? 's' : ''}://`
  const baseUrl = `${protocol}${host}`
```

2022-08-02 16:45 UTC, Ingimarsson commented on apps/web/pages/api/rss/index.ts
> +      : 'https://beta.dev01.devland.is'
Nice, thank you

2022-08-02 16:47 UTC, Ingimarsson commented on apps/web/pages/api/rss/index.ts
> +        <description>Ísland.is</description>
I wanted to, it would ideally have to come from Contentful to be translatable. Will leave it for now.

2022-08-02 16:56 UTC, merged