feat(service-portal): add samgöngustofa scope to client config
island-is/island.is pull request #8128
Opened 2022-08-10 11:21 UTC by disaerna

# Service portal - Samgöngustofa scope

## What

Adding samgöngustofa scope to vehicles client config to access data.

## Why

Samgöngustofa has activated authentication service on their end. 

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-08-11 11:29 UTC, thordurhhh approved these changes
LGTM.

We might want to add this to a file in the scopes folder eventually.
```
libs/auth/scopes
```

2022-08-11 11:32 UTC, thordurhhh commented on libs/clients/vehicles/src/lib/vehiclesClient.config.ts
> +      scope: ['@samgongustofa.is/vehicles-search'],
```suggestion
      scope: ['@samgongustofa.is/vehicle-search'],
```

2022-08-11 11:33 UTC, thordurhhh requested changes
little change request

2022-08-11 11:40 UTC, thordurhhh approved these changes

2022-08-16 12:01 UTC, darrikonn approved these changes

2022-08-16 12:16 UTC, merged