refactor(auth-api): Rename SupportsDelegation to SupportsCustomDelegation
island-is/island.is pull request #8210
Opened 2022-08-23 13:43 UTC by saevarma

https://www.notion.so/eb83399457da4c41a2afeabfb178dcb9?v=d180c0b047504d689094757376bba9db&p=a106ff052b8e472cb3beb3e084048d6e&pm=s

## What

Renaming the `SupportsDelegation` to `SupportsCustomDelegation`

## Why

For clarity as the `SupportsDelegation` can be misunderstood as general support for delegations, when it is only meaning the custom delegations.

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-08-23 16:20 UTC, eirikurn requested changes

2022-08-23 16:20 UTC, eirikurn commented on libs/auth-api-lib/migrations/20220823071133-rename-supportsdelegation-to-supportscustomdelegation.js
> +    )
This migration could cause a lot of pain during release. Can we create a new column instead with the same data as supports_delegation, and clean up the old column later?

2022-08-29 15:55 UTC, eirikurn commented on libs/auth-api-lib/migrations/20220823071133-rename-supportsdelegation-to-supportscustomdelegation.js
> +    queryInterface.removeColumn('client', 'supports_custom_delegation')
Should this be awaited?

```suggestion
    await queryInterface.removeColumn('client', 'supports_custom_delegation')
```

2022-08-30 06:58 UTC, saevarma commented on libs/auth-api-lib/migrations/20220823071133-rename-supportsdelegation-to-supportscustomdelegation.js
> +    queryInterface.removeColumn('client', 'supports_custom_delegation')
Absolutely

2022-08-30 07:43 UTC, eirikurn approved these changes
Sweet!

2022-08-31 07:55 UTC, merged