J s/indictments case files
island-is/island.is pull request #8238
Opened 2022-08-24 19:56 UTC by oddsson

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-08-25 13:49 UTC, Arnarkari93 requested changes
Looks good, just one question.

2022-08-25 14:00 UTC, gudjong requested changes

2022-08-25 14:55 UTC, oddsson commented on apps/judicial-system/api/src/app/modules/file/dto/createFile.input.ts
> +  readonly subtype?: string
Yes! Thanks, fixed.

2022-08-25 14:57 UTC, oddsson commented on apps/judicial-system/api/src/app/modules/file/dto/createFile.input.ts
> +  @Allow()
I set this as an optional field because files uploaded in restriction- and investigation cases have no subtype.

2022-08-26 11:36 UTC, gudjong approved these changes

2022-08-29 10:43 UTC, Arnarkari93 approved these changes

2022-08-29 15:11 UTC, merged