Message for courtStartDate and endDate on same day
island-is/island.is pull request #8250
Opened 2022-08-25 15:13 UTC by oddsson

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-08-25 15:38 UTC, Arnarkari93 requested changes
Nice video demonstration! I have one thought on new location of these messages files

2022-08-25 15:38 UTC, Arnarkari93 commented on apps/judicial-system/web/messages/index.ts
> +export * from '../src/components/AccordionItems/CourtRecordAccordionItem/strings.courtRecordAccordion'
You will need to change the `extract-strings` script in `apps/judicial-system/web/project.json` so that these strings are included.

2022-08-26 08:31 UTC, oddsson commented on apps/judicial-system/web/project.json
> +}
```suggestion
}

```

2022-08-26 09:54 UTC, Arnarkari93 approved these changes

2022-08-26 11:06 UTC, Arnarkari93 requested changes

2022-08-26 11:06 UTC, Arnarkari93 commented on apps/judicial-system/web/project.json
> +        "command": "yarn ts-node -P libs/localization/tsconfig.lib.json libs/localization/scripts/extract 'apps/judicial-system/web/messages/**/*.{js,ts,tsx}' 'apps/judicial-system/web/**/strings.*.{
```suggestion
        "command": "yarn ts-node -P libs/localization/tsconfig.lib.json libs/localization/scripts/extract 'apps/judicial-system/web/messages/**/*.{js,ts,tsx}' 'apps/judicial-system/web/**/*.strings.{js,ts,tsx}'"
```

2022-08-26 17:04 UTC, Arnarkari93 approved these changes

2022-08-29 12:55 UTC, merged