test(ci): acceptance test config values
island-is/island.is pull request #8264
Opened 2022-08-26 18:22 UTC by pshomov

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-08-28 22:24 UTC, busla requested changes
LGTM

minor cosmetics suggestion 😄

2022-08-28 22:24 UTC, busla commented on apps/system-e2e/src/support/utils.ts
> +
```suggestion
const getEnvironmentBaseUrl = (authority: string) => {
  const prefix =
    (process.env.BASE_URL_PREFIX?.length ?? 0) > 0
      ? `${process.env.BASE_URL_PREFIX}-`
      : ''
  return `https://${prefix}${authority}`
}

```

2022-08-30 09:27 UTC, busla approved these changes
LGTM

2022-08-30 09:29 UTC, peturgq approved these changes

2022-08-30 09:36 UTC, merged