chore: update framer-motion
island-is/island.is pull request #8599
Opened 2022-10-05 13:19 UTC by Arnarkari93

[Asana](https://app.asana.com/0/1199153462262248/1203090695199575/f)
## What

- Update `framer-motion` to version 6

## Why

- Not upgrading to latest version (v. 7) since it requires minimum react version 18

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-10-05 13:24 UTC, Arnarkari93 commented on apps/financial-aid/web-veita/src/components/ModalTypes/OptionsModal.tsx
> +          layoutId="inputmodal"
https://www.framer.com/docs/guide-upgrade/##shared-layout-animations

2022-10-05 13:26 UTC, Arnarkari93 commented on apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx
> +          <LayoutGroup>
> Now, components that affect each other's layout can be grouped with LayoutGroup

https://www.framer.com/docs/guide-upgrade/##measuring-layout-changes

2022-10-05 13:30 UTC, Arnarkari93 commented on apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
> -        <AnimateSharedLayout type="crossfade">
Only removed `<AnimateSharedLayout />`

2022-10-06 13:02 UTC, davidpxn commented on apps/financial-aid/web-veita/src/components/InputModal/InputModal.tsx
> +    <AnimatePresence>
This can just be `<>`

2022-10-06 13:02 UTC, davidpxn commented on apps/financial-aid/web-veita/src/components/InputModal/InputModal.tsx
>            layoutId="inputmodal"
We can remove the `layoutId ` prop.

2022-10-06 13:03 UTC, davidpxn commented on apps/financial-aid/web-veita/src/components/ModalTypes/OptionsModal.tsx
> +    <AnimatePresence>
This can just be `<>`

2022-10-06 13:03 UTC, davidpxn commented on apps/financial-aid/web-veita/src/components/ModalTypes/OptionsModal.tsx
> +          layoutId="inputmodal"
We can remove the `layoutId` prop.

2022-10-06 13:30 UTC, davidpxn requested changes
The animation for the `financial-aid` project is looking a bit funky after these changes. 
We don't want the components too animate into each other so we can remove the use of `AnimatePresence` and `layoutId`. I have commented the lines that need to be changed.

2022-10-06 14:51 UTC, davidpxn approved these changes
niicee, looks good 💪

2022-10-10 10:13 UTC, oddsson approved these changes

2022-10-10 10:42 UTC, eirikurn approved these changes
Nice job. Assume all usage has been checked w.r.t. breaking changes. 🎉

2022-10-10 10:55 UTC, merged