chore(j-s): Add fields to case_file table
island-is/island.is pull request #8661
Opened 2022-10-11 14:12 UTC by oddsson

# Add fields to case_file table

[Asana](https://app.asana.com/0/1199153462262248/1203127878754336/f)

## What

Add fields `policeCaseNumber`, `userGeneratedFilename`, `chapter`, and `orderWithinChapter` to the case_file table in DB.

## Why

This is needed for the caseFile feature we are building.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-10-11 14:32 UTC, gudjong requested changes

2022-10-11 14:32 UTC, gudjong commented on apps/judicial-system/backend/migrations/20221011135323-update-case.js
> +  down: (queryInterface, Sequelize) => {
Consider removing `Sequelize` as it is not used

2022-10-12 09:40 UTC, Arnarkari93 reviewed
Looks good, I think here is only one place left.

2022-10-12 09:40 UTC, Arnarkari93 commented on libs/judicial-system/types/src/lib/file.ts
>  export interface CreateFile {
`policeCaseNumber` missing here

2022-10-12 11:24 UTC, Arnarkari93 approved these changes

2022-10-12 11:57 UTC, Arnarkari93 commented on libs/judicial-system/types/src/lib/file.ts
> +  caseId: string
caseId is not part of the CreateFile.dto. It can be removed here. 
```suggestion
```

2022-10-13 09:49 UTC, gudjong approved these changes

2022-10-13 10:05 UTC, merged