fix(application-lifecycle): Lifecycle query optimization
island-is/island.is pull request #8676
Opened 2022-10-12 15:02 UTC by obmagnusson

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-10-14 14:01 UTC, kksteini commented on apps/application-system/api/src/app/modules/application/lifecycle/application-lifecycle.service.ts
> +          prune.application.id,
Console log?
Should this be using logger or is this perhaps running in a client context?

2022-10-14 14:04 UTC, kksteini commented on libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
> +            whenToPrune: 10, // FOR TESTING
Just in case: Was this supposed to change back before hotfix or is it ok to test on prod?

2022-10-14 14:06 UTC, kksteini submitted a review, later dismissed

2022-10-17 14:30 UTC, Thorrik58 requested changes

2022-10-17 14:30 UTC, Thorrik58 commented on apps/application-system/api/src/app/modules/payment/payment.service.ts
> +    console.log({ charge })
console.log

2022-10-17 14:30 UTC, Thorrik58 commented on apps/application-system/api/src/app/modules/payment/payment.service.ts
> +import { unknown } from 'zod'
use a different name as unknownZod or something to differentiate from unknown type

2022-10-17 14:34 UTC, Thorrik58 approved these changes

2022-10-17 14:47 UTC, kksteini commented on apps/application-system/api/src/app/modules/payment/payment.service.ts
> +        : JSON.parse(JSON.stringify(payment.definition))
I would've thought that `JSON.parse(JSON.stringify(someObj)` is equivalent to `someObj`?
Am I missing something?

2022-10-17 15:03 UTC, kksteini approved these changes

2022-10-17 15:04 UTC, kksteini commented on apps/application-system/api/src/app/modules/payment/payment.service.ts
> +        : JSON.parse(JSON.stringify(payment.definition))
I may be thinking this backwards if the norm is that the definition is a string whoops

2022-10-17 15:05 UTC, merged