feat(j-s): Enable file rename on case file screen
island-is/island.is pull request #8748
Opened 2022-10-20 14:20 UTC by oddsson

# Enable file rename on case file screen

[Asana](https://app.asana.com/0/1199153462262248/1203046355378034/f)

## What

Enable file rename on case file screen

## Screenshots / Gifs

https://user-images.githubusercontent.com/3789875/197753083-1a3cdb0f-f4e9-4d42-9eed-e89726169116.mov

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-10-25 10:47 UTC, gudjong approved these changes

2022-10-25 11:30 UTC, Arnarkari93 requested changes

2022-10-25 11:30 UTC, Arnarkari93 commented on apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
> +                  transition={{ duration: 0.5 }}
Consider making this 200ms. Short animations should be under 200ms. Here is a good ref: https://m3.material.io/styles/motion/easing-and-duration/tokens-specs

2022-10-25 11:30 UTC, Arnarkari93 commented on apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
> +                  transition={{ duration: 0.5 }}
Same here

2022-10-25 11:30 UTC, Arnarkari93 commented on apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
> +    updateFilesMutation({
Consider showing toaster if rename of file fails.

2022-10-25 11:30 UTC, Arnarkari93 commented on apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
> +  const [editedFilenames, setEditedFilenames] = useState<EditedFileName[]>([])
I don't quite get why we need to keep `editedFilenames` in a state if we are not rendering them anywhere. Can we discuss this?

2022-10-25 13:36 UTC, Arnarkari93 approved these changes

2022-10-26 12:11 UTC, RunarVestmann approved these changes
Looks good to me

2022-10-26 13:34 UTC, merged