feat(j-s): new indictment case types
island-is/island.is pull request #8874
Opened 2022-11-02 13:45 UTC by Arnarkari93

[Asana - Villa þegar S-mál er stofnað í Auði - misræmi milli undirtegunda](https://app.asana.com/0/1199153462262248/1203270886277905/f)

## What

- feat(j-s): add new case types for indictments
- refactor(j-s): move the indicitment type option map to the web project
- test(j-s): use all indictmentCases list instead of specifying each

## Why

- List has been updated in the court system Auður

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-11-02 13:48 UTC, Arnarkari93 commented on libs/judicial-system/types/src/lib/case.ts
> +  AGGRAVATED_ASSAULT = 'AGGRAVATED_ASSAULT',
sorting list alphabetically

2022-11-02 13:50 UTC, Arnarkari93 commented on apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
> +  const options = useMemo(
Instead of maintaining two lists, we map through the cases an get the label from `caseTypes`

2022-11-02 14:18 UTC, gudjong approved these changes

2022-11-02 14:36 UTC, oddsson requested changes
One thing

2022-11-02 14:43 UTC, Arnarkari93 commented on libs/judicial-system/formatters/src/lib/formatters.ts
> +  THREAT: 'Hótun',
Good catch, this is an oversight

2022-11-03 09:29 UTC, oddsson approved these changes

2022-11-03 10:53 UTC, merged