Website/ More article sorting
island-is/island.is pull request #890
Opened 2020-09-17 14:31 UTC by DavidBachmann

2020-09-17 21:34 UTC, stefanhar commented
We could use aggregation and sorting in elasticsearch to do this, could make the frontend more snappy.
This lays the ground work for that if we want to go that route

2020-09-17 21:39 UTC, stefanhar requested changes

2020-09-17 21:39 UTC, stefanhar commented on libs/api/domains/cms/src/lib/services.ts
> +import { Article, mapArticle } from './models/article.model'
Could this file be here by a misstake?

2020-09-17 22:00 UTC, DavidBachmann commented on libs/api/domains/cms/src/lib/services.ts
> +import { Article, mapArticle } from './models/article.model'
Definitely is

2020-09-18 08:22 UTC, stefanhar approved these changes
LGTM

2020-09-18 09:26 UTC, haukurh approved these changes

2020-09-18 09:28 UTC, arnifreyrs approved these changes
LGTM

2020-09-18 09:36 UTC, darrikonn approved these changes

2020-09-18 09:36 UTC, merged