chore(j-s): Rename Slack events to accommodate S-cases
island-is/island.is pull request #8968
Opened 2022-11-09 09:03 UTC by oddsson

# Rename Slack events to accommodate S-cases

[Asana](https://app.asana.com/0/1199153462262248/1202978837144007/f)

## What

Rename Slack events to accommodate S-cases

## Why

In R-Cases we used to talk about "Krafa". In S-cases it's "Ákæra". We are trying to use more case-agnostic words.

## Screenshots / Gifs

### Slack notifications for S-cases

<img width="697" alt="Screenshot 2022-11-09 at 08 59 08" src="https://user-images.githubusercontent.com/3789875/200786543-6d9fdd07-ee0e-4555-a067-e7cd82041177.png">

### Slack notifications for R-cases

<img width="562" alt="Screenshot 2022-11-09 at 09 33 24" src="https://user-images.githubusercontent.com/3789875/200793820-f0d41efd-88b1-43b8-890d-5c5bb390e813.png">

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-11-09 10:33 UTC, gudjong requested changes
Some comments

2022-11-09 10:33 UTC, gudjong commented on apps/judicial-system/backend/src/app/modules/event/event.service.ts
> +import { CaseType, isIndictmentCase } from '@island.is/judicial-system/types'
Please remove CaseType

2022-11-09 10:33 UTC, gudjong commented on apps/judicial-system/backend/src/app/modules/court/court.service.ts
>    AGGRAVATED_ASSAULT: 'Líkamsáras - sérlega hættuleg',
Please fix this as well. I checked the Auður API and in all cases the correct text is "Líkamsárás...".

2022-11-09 10:33 UTC, gudjong commented on apps/judicial-system/backend/src/app/modules/court/court.service.ts
> +  ASSAULT_LEADING_TO_DEATH: 'Líkamsárás sem leiðir til dauða',
Well spotted 👍

2022-11-09 10:33 UTC, gudjong commented on apps/judicial-system/backend/src/app/modules/event/event.service.ts
>    SCHEDULE_COURT_DATE: ':timer_clock: Kröfu úthlutað fyrirtökutíma',
This event can also happen for indictments. Prosecutors get COURT_DATE notifications for indictments and the event is triggered there.

2022-11-09 10:33 UTC, gudjong commented on libs/judicial-system/formatters/src/lib/formatters.ts
>    ASSAULT_LEADING_TO_DEATH: 'líkamsáras sem leiðir til dauða',
Please also fix this one.

2022-11-11 09:38 UTC, Arnarkari93 approved these changes

2022-11-11 09:57 UTC, gudjong approved these changes

2022-11-14 15:46 UTC, merged