fix(web): Check circularity after mapping models
island-is/island.is pull request #9073
Opened 2022-11-17 14:43 UTC by RunarVestmann

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-11-18 14:57 UTC, siggifv requested changes

2022-11-18 14:57 UTC, siggifv commented on libs/cms/src/lib/search/importers/article.service.ts
> +          logger.warn('Failed to map article', {
Consider logging this as error. Same for the `Circular reference found in article` above.
Apparently, there are many places like this. We should discuss what we should consider as error vs. warning, keeping in mind that we want to know when some data is not being synced/updated, as there is highly likely that someone is making changes in Contentful and waiting for these changes to be appear on the web.

2022-11-21 15:02 UTC, kristofer-lp8f commented on libs/cms/src/lib/search/importers/supportQNA.service.ts
> +              processedEntries.push(entry)
Is this really supposed to be the non-mapped `entry`?
```suggestion
              processedEntries.push(mappedEntry)
```

2022-11-22 10:12 UTC, RunarVestmann commented on libs/cms/src/lib/search/importers/news.service.ts
>    processSyncData(entries: processSyncDataInput<INews>) {
Right, this function could be called something else.

However for example in the article.service.ts file this function is actually processing something (it's removing fields) so one might argue that this function name might be right.

2022-11-23 10:32 UTC, siggifv commented on libs/cms/src/lib/search/importers/article.service.ts
> +          logger.warn('Failed to map article', {
As per our discussions on Slack, we will not be logging these as errors, at least for now. Errors will call the operations team to action, which we don't want to do until we're confident that the indexer will not throw "too many" of those. In the meantime, we'll keep an eye on the logged warnings while we stabilize the indexer code.

2022-11-23 12:53 UTC, siggifv approved these changes

2022-11-23 13:12 UTC, merged