chore(application-system): Application system/introduce statuses to applications
island-is/island.is pull request #9102
Opened 2022-11-21 18:27 UTC by Thorrik58

# Application system/introduce statuses to applications

Attach a link to issue if relevant

## What

Add application statuses to applications template and adjust FormModes on all forms.

## Why

To form a of standard on all application statuses and form modes.

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-11-23 10:57 UTC, obmagnusson approved these changes
LGTM

2022-11-24 09:15 UTC, qdd1 commented on libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
> +          status: 'approved',
Status is still 'inprogress' here. Even VMST has approved application. Applicant could still add information/make changes and send it in again

2022-11-24 09:47 UTC, HelgiHH approved these changes
fsi files lgtm

2022-11-24 10:01 UTC, qdd1 approved these changes
except the comment, lgtm

2022-11-24 11:18 UTC, davidpxn commented on libs/application/templates/financial-aid/src/forms/Spouse.ts
> +  mode: FormModes.DRAFT,
This should be IN_PROGRESS to be consistent with the status in the template

2022-11-24 11:19 UTC, davidpxn requested changes
Just one comment, otherwise the Financial aid files look good 👌

2022-11-24 16:55 UTC, eirikurn approved these changes
Approving core files 🙌

2022-11-25 09:33 UTC, kksteini approved these changes

2022-11-28 20:04 UTC, Thorrik58 commented
@johannaagma and @davidpxn can you verify that your comments have been addressed?

2022-11-29 09:48 UTC, davidpxn approved these changes

2022-11-29 10:49 UTC, merged