chore(j-s): Regression tests
island-is/island.is pull request #9104
Opened 2022-11-22 10:06 UTC by oddsson

# Regression tests

[Asana](https://app.asana.com/0/1199153462262248/1203046355378011/f)

## What

Add regression tests that do not mock out the backend.

## Why

Today, two team members manually run regression tests. If this can be automated, much time can be saved.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2022-11-22 20:38 UTC, gudjong requested changes
Minor issues

2022-11-22 20:38 UTC, gudjong commented on apps/judicial-system/web-e2e-regression/src/integration/Court/RestrictionCases/confirmation.spec.ts
> +  CASES_ROUTE,
Please remove unused import.

2022-11-22 20:38 UTC, gudjong commented on apps/judicial-system/web-e2e-regression/src/utils/index.ts
> +import { resolve } from 'path'
Consider removing unused import.

2022-11-23 09:29 UTC, Arnarkari93 approved these changes
LGTM

2022-11-24 13:27 UTC, gudjong approved these changes

2022-11-24 13:41 UTC, merged