feat(charge-service): Add shouldDeleteCharge field to application state
island-is/island.is pull request #9207
Opened 2022-11-30 10:49 UTC by johannaagma

## What

Add possibility to delete charge even though payment has been fulfilled depending on state.
Check before we delete charge if it has already been deleted.

## Why

To make it possible to refund charge (if already paid) in certain application states.
To prevent error if charge was already deleted while deleting/pruning application.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-11-30 10:55 UTC, sigruntg approved these changes

2022-11-30 16:05 UTC, obmagnusson requested changes
I have some optimization thoughts. As things are we are fetching external data for all applications that should be pruned and that has proven to scale badly if many applications need pruning at once

2022-11-30 16:05 UTC, obmagnusson commented on apps/application-system/api/src/app/modules/application/charge/application-charge.service.ts
> +    application: Pick<Application, 'id' | 'externalData' | 'typeId' | 'state'>,
Should we remove external data here and use the Id from `findPaymentByApplicationId`.

2022-11-30 16:05 UTC, obmagnusson commented on apps/application-system/api/src/app/modules/application/charge/application-charge.service.ts
> +        if (!stateConfig.meta?.lifecycle?.shouldDeleteCharge) {
And instead of checking external data if id exists check `shouldDeleteCharge` beforehand an then try to delete a charge.

2022-11-30 16:08 UTC, obmagnusson commented on libs/application/types/src/lib/StateMachine.ts
> +      shouldDeleteCharge?: boolean | null
Readme update?

2022-12-02 11:26 UTC, obmagnusson commented
> @obmagnusson
> 
> I've made changes, so we always get the chargeID using `findPaymentByApplicationId` instead of looking at externalData (which is actually I should've done from the start I think...).
> 
> But regarding your comment "And instead of checking external data if id exists check shouldDeleteCharge beforehand an then try to delete a charge." - right now I'm calling `findPaymentByApplicationId` for every application we are pruning. I'm wondering which would scale better to do for **every** application we are pruning (to check if application had a payment):
> 
> * Check the template's state config if the application/applicationState has gone through payment. (Note: would need to mark every application state that uses payment, so I need to add a new field to the template state config: "shouldDeleteCharge"). After confirming that the application has gone through payment, then call `findPaymentByApplicationId` to get the chargeID
> * Right away call `findPaymentByApplicationId` to check if there exists a chargeID for the application

Yeah we should go for the "mark as payment state" direction to save db calls. But I think I will include it in another pr with refactoring of the Payment system. For now I think this will suffice.

2022-12-02 11:27 UTC, obmagnusson commented on apps/application-system/api/src/app/modules/application/lifecycle/application-lifecycle.service.ts
> +    'id' | 'attachments' | 'answers' | 'externalData' | 'typeId' | 'state'
Not for now it is needed for some tests

2022-12-02 11:27 UTC, obmagnusson approved these changes

2022-12-02 12:09 UTC, merged