fix(air-discount-scheme): Change hvk to x for non-binary individuals
island-is/island.is pull request #9244
Opened 2022-12-02 10:02 UTC by kksteini

# Why
'x' is preferred over 'hvk'

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Formatting passes locally with my changes
- [X] I have rebased against main before asking for a review

2022-12-02 11:20 UTC, kristofer-lp8f requested changes
Maybe Switch and shared enums?

2022-12-02 11:20 UTC, kristofer-lp8f commented on apps/air-discount-scheme/web/screens/Admin/components/Panel/Panel.tsx
>      return 'manneskja'
Switch statement?

2022-12-02 11:41 UTC, eirikurn approved these changes

2022-12-05 13:28 UTC, kksteini commented on apps/air-discount-scheme/backend/src/app/modules/flight/dto/body.dto.ts
> +  @IsEnum(['kk', 'kvk', 'x'])
Yeah why not

2022-12-05 13:28 UTC, kksteini commented on apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
>      }
Why not? :smile:

2022-12-06 08:57 UTC, kristofer-lp8f approved these changes

2022-12-13 09:42 UTC, merged