J s/step context
island-is/island.is pull request #9259
Opened 2022-12-05 13:18 UTC by oddsson

# Add defender revoked emails for indictments

[Asana](https://app.asana.com/0/1199153462262248/1203046355378001/f)

## What

Add defender revoked emails for indictments

## Why

Defenders need to know if their cases are revoked.

## Screenshots / Gifs

The email is 

```
Ákæra sem taka átti fyrir hjá Héraðsdómi Reykjavíkur fimmtudaginn 1. desember 2022, kl. 12:32, hefur verið afturkölluð.

Sakborningur: Bragagata 2, fd. 12.12.2000.

Dómstóllinn hafði skráð þig sem verjanda í málinu.
```

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-12-14 12:05 UTC, oddsson commented on libs/island-ui/core/src/lib/FormStepper/SubSections/SubSections.tsx
> +              onClick={subSection.onClick}
```suggestion
```

2022-12-14 14:37 UTC, Arnarkari93 requested changes
Good work! I have some suggestions/nitpicks.

2022-12-14 14:37 UTC, Arnarkari93 commented on apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
> +        setModalVisible(true)
Consider refactoring the use of these `nextRoute` states to be a part of setting the modal to visible. That way you will never render a modal that expects a destination route without one. This applies to all use-cases of this `nextRoute` states.

2022-12-14 14:37 UTC, Arnarkari93 commented on apps/judicial-system/web/src/utils/formHelper.ts
> +    ),
We do not need to run all the validation functions until the `caller` of this function has decided which routes to validate.
```suggestion
export const stepValidations = (): stepValidationsType => {
  return {
    [constants.CREATE_RESTRICTION_CASE_ROUTE]: (theCase: Case) => validations.isDefendantStepValidRC(
      theCase,
      theCase.policeCaseNumbers,
    ),
    [constants.CREATE_TRAVEL_BAN_ROUTE]: (theCase: Case) validations.isDefendantStepValidRC(
      theCase,
      theCase.policeCaseNumbers,
    ),
```

2022-12-14 14:37 UTC, Arnarkari93 commented on apps/judicial-system/web/src/utils/formHelper.ts
> +}
```suggestion
export const findFirstInvalidStep = (steps: string[], theCase: Case) => {
  const validations = stepValidations()
  const validationFunctions = Object.entries(validations)
  const stepsToCheck = validationEntries.filter(([key]) => steps.includes(key))

  if (stepsToCheck.every(([, validationFn]) => validationFn(theCase) === true)) {
    return steps[steps.length - 1]
  }

  const [key] = stepsToCheck.find(([, validationFn]) => validationFn(theCase) === false) || []
  return key
}
```

2022-12-14 14:37 UTC, Arnarkari93 commented on libs/island-ui/core/src/lib/FormStepper/SubSectionItem/SubSectionItem.tsx
> +      ) : onClick && currentState !== 'active' ? (
Do we need these changes after introducing the V2?

2022-12-16 11:43 UTC, Arnarkari93 approved these changes
🙌

2022-12-16 12:46 UTC, merged