fix(j-s): remove duplicates when displaying indictment subtypes
island-is/island.is pull request #9316
Opened 2022-12-13 10:31 UTC by Arnarkari93

[Asana - Endurtekning á undirtegund ákæru](https://app.asana.com/0/1199153462262248/1203532045215674/f)
## What

- Remove duplicates when displaying indictment subtypes

## Why

- It is not relevant information to see the same subtype appear more than once in a overview

## Screenshots / Gifs

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Formatting passes locally with my changes
- [X] I have rebased against main before asking for a review

2022-12-13 12:01 UTC, oddsson requested changes
Could you please do something similar for slack notifications? (see screenshot on Asana task)

2022-12-14 11:48 UTC, Arnarkari93 commented
> Could you please do something similar for slack notifications? (see screenshot on Asana task)

Its used by both the frontend and backend code. Here is the call from the `event.service.ts`
https://github.com/island-is/island.is/blob/f44bdffb22335fcb771d6474a6b4f9efce1ac048/apps/judicial-system/backend/src/app/modules/event/event.service.ts#L76-L94

2022-12-14 12:10 UTC, oddsson commented
> > Could you please do something similar for slack notifications? (see screenshot on Asana task)
> 
> Its used by both the frontend and backend code. Here is the call from the `event.service.ts`
> 
> https://github.com/island-is/island.is/blob/f44bdffb22335fcb771d6474a6b4f9efce1ac048/apps/judicial-system/backend/src/app/modules/event/event.service.ts#L76-L94

Ah! Ofcorse

2022-12-14 12:10 UTC, oddsson approved these changes

2022-12-14 13:37 UTC, merged