feat(transfer of vehicle ownership): Update data provider
island-is/island.is pull request #9356
Opened 2022-12-15 14:43 UTC by johannaagma

## What

Update data providers for Transfer of vehicle ownership

## Why

Make changes to data providers so the application works

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2022-12-16 11:08 UTC, obmagnusson commented
Could these providers be shared?

2022-12-19 11:27 UTC, obmagnusson requested changes

2022-12-19 11:27 UTC, obmagnusson commented on libs/application/template-api-modules/src/lib/modules/shared/api/vehicles/vehicles.service.ts
> +      } else if (showOwned && showCoOwned && !showOperated) {
Fix lint error. Also not really clear how this error flow with the parameters is suppposed to work. You might want to consider some basic documentation on usage.

2022-12-19 12:08 UTC, sigruntg approved these changes

2022-12-19 12:14 UTC, obmagnusson approved these changes
Awesome! Another shared provider 🚀 💯

2022-12-20 15:35 UTC, thordurhhh approved these changes
💯

2022-12-20 15:56 UTC, merged