feat(judicial-administration): Client
island-is/island.is pull request #9560
Opened 2023-01-10 13:11 UTC by kksteini

Judicial administration client.

## What

Add client connection for judicial administration so that we can check court bankruptcy status for operating license application.

And some minor changes to the application.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2023-02-20 13:21 UTC, saevarma requested changes

2023-02-20 13:21 UTC, saevarma commented on libs/clients/judicial-administration/src/lib/judicialAdministration.service.ts
> +      .withMiddleware(new AuthMiddleware(auth))
This forwards the current island.is access token as the Authorization header which we shouldn´t do. 
Does this api require any HTTP authentication or is it always as part of the request?

2023-02-20 13:21 UTC, saevarma commented on libs/clients/judicial-administration/src/lib/providers.ts
> +  SearchBankruptcyHistoryApi,
Are you only using the `AuthenticateApi` and `SearchBankruptcyHistoryApi`?
I would only add the used apis in exported apis, and add the other on demand.

2023-02-20 13:21 UTC, saevarma commented on libs/clients/judicial-administration/src/lib/judicialAdministration.types.ts
> +export interface CriminalRecord {
Is this unused?

2023-02-20 13:24 UTC, saevarma requested changes

2023-02-20 13:24 UTC, saevarma commented on libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts
> +      console.log(value.bankruptcyStatus)
console.log

2023-02-20 17:45 UTC, Toti91 commented on libs/application/core/src/lib/messages.ts
> +  },
Any reason why these translation strings are in `application/core` instead of just the template?

2023-02-21 14:54 UTC, alexdiljar commented on libs/clients/judicial-administration/project.json
> +  "tags": []
I get this eslint error, even after adding the "lib:client" tag an yarning again, is there anything I can do to fix this?
`A project tagged with "scope:application-system-api" can only depend on libs tagged with "lib:api", "lib:application-system-api", "lib:application-system", "lib:client", "lib:nest", "lib:node", `

2023-02-22 16:32 UTC, saevarma approved these changes
Core files LGTM

2023-02-22 16:42 UTC, alexdiljar approved these changes
@kksteini approved as well but since he created the pr he couldn't review

2023-02-22 17:16 UTC, krrrrrrrrrrr approved these changes

2023-02-27 16:53 UTC, merged