Feat applications draft status bar
island-is/island.is pull request #9683
Opened 2023-01-19 17:14 UTC by egill15

# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-01-23 15:10 UTC, disaerna approved these changes
Code owned file looks good

2023-02-06 11:19 UTC, obmagnusson requested changes
Minor comment

2023-02-06 11:19 UTC, obmagnusson commented on libs/application/templates/public-debt-payment-plan/src/forms/PrerequisitesForm.ts
> +  mode: FormModes.NOT_STARTED,
Might want to mention this setup in the readme.

2023-02-07 16:25 UTC, obmagnusson commented on libs/application/core/README.md
> +- `notstarted` The user has opened the application / it is saved in the database, but is not listed yet (etc still in prerequisites)
```suggestion
- `notstarted` The user has opened the application / it is saved in the database, but is not listed yet (eg. still in prerequisites)
```

2023-02-07 16:27 UTC, obmagnusson approved these changes
LGTM

2023-02-13 12:31 UTC, albinagu approved these changes
island-ui lgtm

2023-02-13 13:12 UTC, merged