feat(new application): Update instructor in driving license book
island-is/island.is pull request #9753
Opened 2023-01-27 09:46 UTC by johannaagma

## What

Create new application so that students can update the instructor in their driving license book

## Why

So that students can choose another instructor that is conntected to their driving license book

## Screenshots / Gifs

![image](https://user-images.githubusercontent.com/6495412/215056462-187476eb-967f-4921-878c-160448fa1c56.png)

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

2023-01-27 12:16 UTC, kristofer-lp8f reviewed
LGTM

Minor comments

2023-01-27 12:16 UTC, kristofer-lp8f commented on libs/application/template-api-modules/src/lib/modules/templates/driving-license-book-update-instructor/driving-license-book-update-instructor.service.ts
> +    const newInstructorSsn = answers?.newInstructor?.nationalId
Missing nullish check & throw

2023-01-27 12:16 UTC, kristofer-lp8f commented on libs/application/templates/driving-license-book-update-instructor/README.md
> +Run `nx test application-templates-driving-license-book-update-instructor` to execute the unit tests via [Jest](https://jestjs.io).
Would be nice to get a description of the application here

2023-01-27 12:16 UTC, kristofer-lp8f commented on libs/application/templates/driving-license-book-update-instructor/src/assets/Jobs.tsx
> +export const Jobs: FC = () => (
Steve Jobs? An SVG image of the Apple king?

2023-01-27 12:16 UTC, kristofer-lp8f commented on libs/application/templates/driving-license-book-update-instructor/src/lib/DrivingLicenseBookUpdateInstructorTemplate.ts
> +  },
This looks like something which might be shared in e.g. `libs/shared`

2023-01-27 12:16 UTC, kristofer-lp8f commented on libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts
> +    }
Personal vandetta against `try...catch` blocks
```suggestion
      }).catch(()=> {success: false})
      return {success: true}
```

2023-01-27 12:17 UTC, kristofer-lp8f commented on libs/application/template-api-modules/src/lib/modules/templates/driving-license-book-update-instructor/driving-license-book-update-instructor.service.ts
> +    const newInstructorSsn = answers?.newInstructor?.nationalId
I.e. will the call a few lines lower crash if `newInstructorSsn` is nullish?

2023-01-27 12:18 UTC, kristofer-lp8f commented on libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts
> +  async updateActiveStudentBookInstructor(
Please add a test for this new function

2023-01-30 15:37 UTC, obmagnusson requested changes

2023-01-30 15:37 UTC, obmagnusson commented on libs/application/template-api-modules/src/lib/modules/templates/driving-license-book-update-instructor/driving-license-book-update-instructor.service.ts
> +import { DrivingLicenseBookService } from '@island.is/api/domains/driving-license-book'
We dont want the application system to depend on the api.  You should communicate with the  client library directly  instead.

2023-01-31 13:59 UTC, obmagnusson approved these changes
Awesome!

2023-02-06 17:29 UTC, eirikurn approved these changes

2023-02-07 15:10 UTC, kristofer-lp8f approved these changes
Wonderful changes :)

2023-02-07 15:10 UTC, kristofer-lp8f commented on libs/clients/driving-license-book/src/lib/__mock-data__/requestHandlers.ts
> +      const body = req.body as any
```suggestion
      const body = req.body as unknown
```

2023-02-07 19:05 UTC, merged