fix(j-s): Registrar Indictment Completion
island-is/island.is pull request #9773
Opened 2023-01-30 18:37 UTC by gudjong

# Registrar Indictment Completion

[Dómritarar geta ekki lokið ákærum](https://app.asana.com/0/1199153462262248/1203705883653532/f)

## What

- Adds an optional callback to roles rules given the rules access to the request.
- Modifies registrar transition rule to allow registrars to complete indictment cases.
- Creates a new defender file rule to limit defender case file access to indictment ruling only.

## Why

- Bug fixes and improved security.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

2023-01-30 21:05 UTC, oddsson commented on apps/judicial-system/backend/src/app/modules/file/test/fileController/updateFilesGuards.spec.ts
> +import { CaseFileExistsGuard } from '../../guards/caseFileExists.guard'
This is never used, please remove it.

2023-01-30 21:06 UTC, oddsson commented on libs/judicial-system/auth/src/lib/auth.types.ts
> +type RolessBasicRule = {
```suggestion
type RolesBasicRule = {
```

2023-01-30 21:08 UTC, oddsson commented on libs/judicial-system/auth/src/lib/auth.types.ts
> +  | RolessBasicRule
```suggestion
  | RolesBasicRule
```

2023-01-30 21:09 UTC, oddsson requested changes
Just a couple of minor things

2023-01-31 08:09 UTC, gudjong commented on libs/judicial-system/auth/src/lib/auth.types.ts
> +  canActivate?: (request: any) => boolean
Not really as then I need to use the dreaded `as` in each `canActivate` method defined in the roles rules. I struggled with this a bit and then gave up.

2023-01-31 08:56 UTC, oddsson approved these changes

2023-01-31 13:55 UTC, merged